### ISSUE TITLE
Setting to filter repos by organization

### ISSUE THREAD

**Issue by oddityoverseer13** [gitskarios/Gitskarios#100]
It'd be nice to have a view that only shows *my* repos (not a mix of my repos + my organization's repos).

**Comment by alorma** [comment]
Ok, after moving Gitskarios to @gitskarios, i will add a NavDrawer entry with organization repositories

**Comment by pcqpcq** [comment]
moving Gitskarios to @gitskarios?

**Comment by alorma** [comment]
U_u, sorry.

I cut my words: after moving all repo to an Organization, i get the problem of mixing repos, so i will split it

**Comment by alorma** [comment]
In fact, that was a change from the GitHub API, as you can read there:

https://developer.github.com/v3/repos/#list-your-repositories

So i will not split that, because i will follow the API.
