### ISSUE TITLE
Materialize

### ISSUE THREAD

**Issue by alorma** [gitskarios/Gitskarios#101]
Hi.

I open this issue (and milestone) to discuss what material guidelines should be implemented, and where they are break.

@afollestad @mikepenz I ask you as a Material awesome libraries developerse what's your opinion?

**Comment by mikepenz** [comment]
@alorma one of the things i've seen is the wrong height of the items in the source section of an repository

the back button behavior is still not consistent or it will always bring you to your homescreen. it won't navigate back to the home of the app first.

**Comment by alorma** [comment]
People & Orgs back button is already fixed:

https://github.com/alorma/Gitskarios/issues/90

The divider in people & orgs, it should be full width? I think it looks better as is now, i don't like too much full dividers

**Comment by MDXDave** [comment]
Is it possible to hide the FAB on scrolling down and show it again when scrolling up?

**Comment by eliseealex** [comment]
I think, it will be great to duplicate features on floating button.
For example on "Source" and "Commits" tabs there are floating button action to change the branch, but it will be more convenient to change branch also by clicking on its name at the bottom.
![device-2015-05-24-115251](https://cloud.githubusercontent.com/assets/4640201/7787125/34d16634-0203-11e5-9bcc-5144b2e73b6d.png)

**Comment by eliseealex** [comment]
Also on code view tab arrow is thicker than on source tab.
![device-2015-05-24-115251](https://cloud.githubusercontent.com/assets/4640201/7787131/dae93a38-0203-11e5-890e-83e451792044.png)
![device-2015-05-24-115507](https://cloud.githubusercontent.com/assets/4640201/7787132/daea7236-0203-11e5-92c5-4e8c789b7752.png)

**Comment by eliseealex** [comment]
May be floating button is not a right place for up action. As for me arrow on action bar should do that instead.

**Comment by alorma** [comment]
Hi.

Thanks for that, i was thinking on reduce the number of floating actions buttons in the app, and this is a good aproach to start
