### ISSUE TITLE
Title in toolbar is not properly aligned on landscape mode

### ISSUE THREAD

**Issue by robertmathew** [gitskarios/Gitskarios#102]
![screenshot_2015-04-18-00-04-01](https://cloud.githubusercontent.com/assets/2344947/7214244/cb08f112-e5c0-11e4-8c61-8a8cee95fb80.png)

Font size needed to be corrected also.
This condition is on every activity.

**Comment by robertmathew** [comment]
I think font size is correct.

**Comment by alorma** [comment]
Hey.

Thanks for that, i read a bit in stackoverflow and it seems it's a problem with appcompat. There is a solution that i will implement
