### ISSUE TITLE
Wrong string in "Star" progress window for repositories

### ISSUE THREAD

**Issue by smiley** [gitskarios/Gitskarios#104]
When you tap "Star" for a repository, the progress window comes up with the wrong string -- "Starring user...". However, unstarring uses the correct string: "Unstarring repo..."

**Comment by smiley** [comment]
And right after I reported this, as the issue was loading a toast popped up saying "Issue not found" and the loading window persisted forever. Had to close and re-open the app.

Note that as I wrote the issue, I opened another repository from another Chrome window to re-check what the wrong string was exactly, and I tapped the back button to return to the Create Issue view. This flow may have affected something in the state that caused this bug.

**Comment by smiley** [comment]
One more wrong string -- opening a file like "README.md" says "Adding comment...".

**Comment by alorma** [comment]
Done, merci!
