### ISSUE TITLE
Can't close the app on Version 2.3.5(235)

### ISSUE THREAD

**Issue by robertmathew** [gitskarios/Gitskarios#108]
Back button is not working on My repositories.

Reproduce the issue:
Open the app -> select the event -> press back button. The app doesn't close.

**Comment by alorma** [comment]
Hi.

I can't reproduce that.

What steps are you doing? Open app, open drawer, Events, and select one?

**Comment by robertmathew** [comment]
Open app -> drawer -> events -> press back button -> directed to my repositories -> press the back button. Now the app does not close and my repositories view are refreshed on pressing the back button.

**Comment by robertmathew** [comment]
Same issue on Samsung Galaxy S3 and Galaxy Note 10 GT-N8000

**Comment by alorma** [comment]
Yes. I reproduced it yesterday.

I will try to fix it soon.

**Comment by robertmathew** [comment]
Thanks. Great.
