### ISSUE TITLE
Not found error after adding issue

### ISSUE THREAD

**Issue by MDXDave** [gitskarios/Gitskarios#110]
After adding an issue, the following error message is shown:

**Comment by MDXDave** [comment]
There was an issue loading username/Repository #0 Not found 

If you click on accept the issue list is shown, if you click on retry the error appears again.

**Comment by MDXDave** [comment]
![screenshot_2015-04-25-12-56-16](https://cloud.githubusercontent.com/assets/6099976/7332667/fe13da92-eb4a-11e4-8fa7-97abcd357d52.png)

**Comment by alorma** [comment]
Yes, i know that.

Sometimes can't get the id of created issue, i will take a look at that.
