### ISSUE TITLE
Action bar Gist

### ISSUE THREAD

**Issue by Olivier-Daire** [gitskarios/Gitskarios#111]
When editing a gist, if you select the text, it shows the the action bar on the top of the screen but without any icon. However you can click on the blank action bar and it will copy the text, allow you to share it...

Nexus 4 - Lollipop 5.1

![screenshot_2015-04-26-15-07-32](https://cloud.githubusercontent.com/assets/6728295/7337341/01a63cea-ec27-11e4-82d0-191ad1c21d56.png)

**Comment by alorma** [comment]
Ups!

That was because a change on how actionbar works.

I will fit it soon

**Comment by Olivier-Daire** [comment]
Great, thanks !
