### ISSUE TITLE
Organizations not shown

### ISSUE THREAD

**Issue by Cyruxx** [gitskarios/Gitskarios#116]
I don't see my organizations in this app.

**Comment by alorma** [comment]
Are these organizations private or public?

Where you can't see? From profile? From people & orgs?

**Comment by Cyruxx** [comment]
It is a public organization and it's not shown everywhere.

Profile: 0 organizations
People & Orgs: No entries

**Comment by alorma** [comment]
Fixed

**Comment by Cyruxx** [comment]
Still missing one organization.  The other one's shown

**Comment by alorma** [comment]
Cyruxxx, recently github changed how organization permissions are granted.

As you can read here: https://developer.github.com/changes/2015-01-07-prepare-for-organization-permissions-changes/

You need to go to your settings, select Applications, and there go to Gitskarios, then, enable gitskarios to grant permission for the org.

**Comment by vsimonian** [comment]
@alorma Would there be any way to automate some sort of prompt to ask for org permissions or to notify the user that steps need to be taken for access to be granted to the app? I had no idea that this was a permissions issue and was about to submit a bug thinking it was a problem with the app until I found this issue. :)

**Comment by alorma** [comment]
Hey, yes.

In the next release i will provide a dialog with an explanation :)

I can't automate this, because it's something that i can't do throw the api :(

**Comment by Cyruxx** [comment]
@alorma Just make a notification with the Link to the applications area (http://github.com/settings/applications) and a small description. I think that'd be enough. :-)

**Comment by vsimonian** [comment]
@alorma That'd be fantastic. You're awesome! :+1:
@Cyruxx Sounds simple enough! :smiley:
