### ISSUE TITLE
Add new account activity blank

### ISSUE THREAD

**Issue by Rhedox** [gitskarios/Gitskarios#117]
I recently reinstalled the app and was unable to log in because the Add Account screen I get at the beginning is black except for the toolbar. http://imgur.com/ru5p5XG
Im running CM 12.1 (Android 5.1.1) on a Galaxy S4.

**Comment by alorma** [comment]
Yes. You should click on Add account now, it uses external login :)

**Comment by Rhedox** [comment]
I'm sorry.

I expected it to show a web view. That should be more obvious to the user though. Maybe place a dedicated button on the activity.

**Comment by alorma** [comment]
Thanks for that.

I will modify this screen to have more sense :)
