### ISSUE TITLE
App crash on add account from system

### ISSUE THREAD

**Issue by alorma** [gitskarios/Gitskarios#119]

**Comment by arkadiytehgraet** [comment]
Hey, what's the status of this issue? It seems I can't reproduce it

**Comment by alorma** [comment]
It seems only happens on lollipop, i will fix it soon :disappointed_relieved:

**Comment by arkadiytehgraet** [comment]
I was testing it on lolipop, couldn't reproduce. Pulled the latest commit
on develop branch before trying to reproduce it
23 июля 2015 г. 23:05 пользователь "Bernat Borrás Paronella" <
notifications@github.com> написал:

**Comment by alorma** [comment]
Oh ok, it's fixed :)
