### ISSUE TITLE
 store location on issue-detail-overviw

### ISSUE THREAD

**Issue by Hauwertlhaufn** [gitskarios/Gitskarios#120]
If I open a issue-detail and want to get back to the overview, it automaticly goes to the newest one.
If there is a repository with many issues, it is very annoying scrolling down the whole thing again.
So a function, that stores the location at the issue-detail-overviw, while you have opened a repo, would be very helpful.
(Nexus 5, Android 5.1 with GitSkarios 2.3.6)

**Comment by alorma** [comment]
I think is fixed now.
