### ISSUE TITLE
README prints raw html and encoding errors

### ISSUE THREAD

**Issue by hj332921** [gitskarios/Gitskarios#122]
the raw html sources are printing in README field. And it cannot print non-alphabet correctly, like Korean or Chinese.

**Comment by hj332921** [comment]
Sorry for my mistake! 
encodimg > encoding

**Comment by hj332921** [comment]
Sorry for my mistake! 
encodimg > encoding

**Comment by alorma** [comment]
Hey.

Chinese (UTF-8) characters was fixed.

Can you provide me an example?

**Comment by hj332921** [comment]
My repository, [AraLanguage](https://github.com/hj332921/AraLanguage), is using Korean README. And I cannot see correctly on your app. I think Chinese characters are fixed but Korean didn't.

**Comment by alorma** [comment]
![screenshot_2015-05-06-18-37-07](https://cloud.githubusercontent.com/assets/887462/7498179/2e17f61a-f41f-11e4-9d0a-bb693504bff7.png)

I just download the app and tried your repository.

It shows ok for me.

What is your device language?

**Comment by hj332921** [comment]
I'm using Korean, with Samsung Galaxy S3. My screen is not the same with yours, What I can see is only html tags like <h1>. not only my project, but all projects include this project shows html tags on README section.

**Comment by hj332921** [comment]
This is the text which can I see on Gitskario README:
```
<h1>
<a id="user-content-readme" class="anchor" href="#readme" aria-hidden="true"><span class="octicon octicon-link"></span></a>README</h1>

<h2>
<a id="user-content-fork" class="anchor" href="#fork" aria-hidden="true"><span class="octicon octicon-link"></span></a>FORK</h2>

<p>Thanks dev for forking Gitskarios!</p>

<p>Since now, if you want to use your own version of Gitskarios, you should generate specific App on Github</p>

...SNIP...
```

**Comment by alorma** [comment]
Uhmmm, ok, so in your app all readme contents shows <html> tags instead formatted text, is that?

**Comment by hj332921** [comment]
Exactly right. I cannot realize why this error occured. I'm using Galaxy S3, JellyBean, Korean locale.

**Comment by alorma** [comment]
Should be fixed in new version

**Comment by aivus** [comment]
Hi. I have the same issue with all readme files.

My app build: 68c226a
In which version it's fixed?

**Comment by alorma** [comment]
It's in dev version yet, i not uploaded it yet
