### ISSUE TITLE
Contributors tab is not loaded by default

### ISSUE THREAD

**Issue by eliseealex** [gitskarios/Gitskarios#126]
On Nexus 5, Android 5.1, Contributors tab in any project is not loaded by default. Am I the one who has this problem?

**Comment by alorma** [comment]
Hi @eliseealex no, you are not the only one :(

I will check that in the next release, thanks for the feedback

**Comment by eliseealex** [comment]
Thanks for your attention. I like your application and i will try to help you with some more issues and may be pull requests if i would have enough knowledge.

**Comment by alorma** [comment]
All kind of support is welcome :)

**Comment by arkadiytehgraet** [comment]
What's the status of the issue? I can't reproduce it

**Comment by alorma** [comment]
I think is fixed now.

I will release in next version

**Comment by arkadiytehgraet** [comment]
Cool, thanks :)
