### ISSUE TITLE
Render rst documents

### ISSUE THREAD

**Issue by miki725** [gitskarios/Gitskarios#128]
Many of the Python repositories use restructured text for readme files and documentation in general. Currently they are not correctly rendered within the app but are correctly rendered on GitHub.

**Comment by miki725** [comment]
![screenshot_2015-05-26-06-39-35](https://cloud.githubusercontent.com/assets/932940/7810712/909983e6-0372-11e5-9e7d-d2063fa67dd6.png)

**Comment by alorma** [comment]
Uhmmm

Can you give me an example repository?

I changed how readme files are shown, maybe, hope it fix

**Comment by miki725** [comment]
here is one - https://github.com/miki725/django-sqrl

**Comment by miki725** [comment]
btw, thanks for super fast reply. did not expect anything so fast!

**Comment by alorma** [comment]
Answer is easy... fix that bug i don't know :)
