### ISSUE TITLE
The background of the readme file is gray

### ISSUE THREAD

**Issue by rocboronat** [gitskarios/Gitskarios#129]
It sould be white, to be consistent with the white backgroud of the readme file at the website.

**Comment by alorma** [comment]
I think pure White don't look good in mobile devices

**Comment by rocboronat** [comment]
Whow. If you don't like pure white in backgrouds, why the source screen backgroud is white, the commit list is white, and also the issues list and the contributors one are white? There are 5 tabs, all of them with white background except the readme screen.
