### ISSUE TITLE
Add instruction for clonning and starting application to readme

### ISSUE THREAD

**Issue by eliseealex** [gitskarios/Gitskarios#131]
I tried to clone application and faced several problems with starting it up first time.

In [gradle.properties](https://github.com/gitskarios/Gitskarios/blob/master/gradle.properties) file there are properties:
```Groovy
# API CLIENTS
DEV_ID={dev_app_id}
DEV_SECRET={dev_app_secret}
DEV_CALLBACK={dev_app_callback}

PRO_ID={pro_app_id}
PRO_SECRET={pro_app_secret}
PRO_CALLBACK={pro_ap_callback}
```

Without "GH_" prefix, but to compile ':sdks:GithubAndroidSdk' dependency gradle need properties with "GH_" prefix, is this a feature or bug? To compile I've uncommented properties and added "GH_".
```Groovy
# API CLIENTS
GH_DEV_ID={dev_app_id}
GH_DEV_SECRET={dev_app_secret}
GH_DEV_CALLBACK={dev_app_callback}

GH_PRO_ID={pro_app_id}
GH_PRO_SECRET={pro_app_secret}
GH_PRO_CALLBACK={pro_ap_callback}
```

Commands to clone repository:
```
git clone https://github.com/gitskarios/Gitskarios.git
git submodule update --recursive --init 
```

**Comment by alorma** [comment]
Hi.

Nice to see someone want's to fork that :D, maybe a PR is coming soon?

I need to check my grdle.properties, i'm not at home now.

The GH_ prefix was added because i started to work on something new, and needes some different api keys, but it should work with just that. I will check and update readme content as soon as possible

**Comment by eliseealex** [comment]
Hi, ok =)
I hope PR will be soon. I want to make some small usability improvements. 

Can you give me an advice about issues lifecycle here? Should i report a new issue and you will assign it to me? Or how else can i be sure that i will not repeat something that you've already changed in some other branch?

**Comment by alorma** [comment]
uhmm...

I usually work at develop branch, when i do feature branch, is because i want to test something that i'm not sure about that change.

I can't assign issues to you because you are not a contributor of the repository

**Comment by eliseealex** [comment]
Well, thanks. 

So, anyway, I can still add issues to that repository and mark that i'm working on them in the comments. Or is it unnecessary?
