### ISSUE TITLE
User can't login if there is a default application for github url

### ISSUE THREAD

**Issue by eliseealex** [gitskarios/Gitskarios#132]
Now when user is trying to log in, application creates an implicit intent to redirect user to github url, but if there is any application that processes all github url intents (for example [forkhub](https://play.google.com/store/apps/details?id=jp.forkhub&hl=ru)) he will fail to login.

I think it will be better to use WebView instead of implicit intent.

**Comment by alorma** [comment]
NO!

I used webviews before, and had several problems with that.

Maybe, a better aproach, is creating a custom intent, deleting other applications like forkhub, octodroid, or modernhub)

**Comment by eliseealex** [comment]
Ok, so you think it will be better to simply exclude applications by their names?

**Comment by alorma** [comment]
> Ok, so you think it will be better to simply exclude applications by their names?

No by their names...

Maybe, a better aproach, is get the apps that can receive github.com and remove them :D

**Comment by eliseealex** [comment]
Remove them from phone?) How?

**Comment by alorma** [comment]
nooo XD

From intent.
Query activities with packagemanager, that can get links from github.com, and not use them in th eintent

**Comment by eliseealex** [comment]
Aha, i agree, i meant it when i said "by names".

**Comment by alorma** [comment]
ok :D

**Comment by eliseealex** [comment]
I think, it will be better to make it vice versa, like [there](http://stackoverflow.com/questions/18682833/how-to-exclude-a-specific-application-from-action-view-intent), find user browsers like that:
```Java
Intent i = new Intent(Intent.ACTION_VIEW, Uri.parse("http://someurl.com"));
List<ResolveInfo> list = context.getPackageManager().queryIntentActivities(i, 0);
```
And then use them to limit intent like that:
```Java
Intent i = new Intent(Intent.ACTION_VIEW);
i.setData(Uri.parse(url));
ComponentName comp = new ComponentName("com.android.browser", "com.android.browser.BrowserActivity");
i.setComponent(comp);
```

What do you think?

**Comment by alorma** [comment]
Uhm...

As an example, i use Lolipop in Nexus 5, native one, so i don't have the default android browser.

Quering for any url is not good, because we want to know which apps are filtering github.com

You tried that? [Intent intercept](https://play.google.com/store/apps/details?id=uk.co.ashtonbrsc.android.intentintercept) ? With this one, you can se how intent is launched, and make the correct filter on Intent.

**Comment by eliseealex** [comment]
I meant, that there:
```Java
ComponentName comp = new ComponentName("com.android.browser", "com.android.browser.BrowserActivity");
```
Should be all users browser, which we can get by this command:
```Java
Intent i = new Intent(Intent.ACTION_VIEW, Uri.parse("http://someurl.com"));
List<ResolveInfo> list = context.getPackageManager().queryIntentActivities(i, 0);
```

**Comment by alorma** [comment]
Uhmm ok

But, why not query for http://github.com, and then filter by apps that are browsers? hen, show a custom Dialog to be redirected to, not let system do the work?

**Comment by eliseealex** [comment]
In this case we should always had an actual browser list. I want to use custom url to get all browsers list.
And then we can do intersection of all browsers (all applications, that can process custom url) and apps that can process http://github.com.

**Comment by alorma** [comment]
uhmmm, ther's no way to get a lost of browsers?

Something like:

```
Intent i = new Intent(Intent.ACTION_VIEW, Uri.parse("http://*"));
List<ResolveInfo> list = context.getPackageManager().queryIntentActivities(i, 0);
```

**Comment by alorma** [comment]
Ok, settings the component name seems to be the best option.

Try that! :D

**Comment by alorma** [comment]
Closed by PR
