### ISSUE TITLE
Edit comments

### ISSUE THREAD

**Issue by nomad71** [gitskarios/Gitskarios#134]
It seems Gitskarios doesn't allow you to edit your comments/issues. That would be a nice thing to have!

Thanks!

**Comment by alorma** [comment]
Not allow for now yet, i want to add it

**Comment by alorma** [comment]
Soon...

**Comment by mmoayyed** [comment]
:+1: great idea. please do this.

**Comment by mmoayyed** [comment]
Also, please allow for deletes as well.
