### ISSUE TITLE
Back arrow and back button have different behavior on Login activity

### ISSUE THREAD

**Issue by eliseealex** [gitskarios/Gitskarios#137]
Back arrow and back button have different behavior on Login activity if user comes from application and want to add new account to existing. If user press back button application finishes, if user press back arrow application returns to application.

**Comment by zacharyparrish** [comment]
Has anyone touched this? I'd like to help contribute. I can work on this.

**Comment by alorma** [comment]
You are welcome to contribute with that :)

**Comment by zacharyparrish** [comment]
Getting "Error:Configuration with name 'debug' not found." when opening the project in Android Studio. Seen this before?

**Comment by alorma** [comment]
Maybe is a problem with configuration, look at GithubAndroidSDK readme for info

**Comment by alorma** [comment]
@zacaryparrish solved?

**Comment by zacharyparrish** [comment]
Haven't had time to check. I'm currently away from home.

**Comment by zacharyparrish** [comment]
@alorma still having the same issue. Followed the usage instructions on the README.

**Comment by alorma** [comment]
can't check now, i will try tomorrow

**Comment by arkadiytehgraet** [comment]
I have this issue as well.

**Comment by alorma** [comment]
Did you guys updated to last develop branch commits?

**Comment by arkadiytehgraet** [comment]
I've forked the repo 2 hours ago. `git pull` tells me 'Already update'. However, it seems like I've figured out the issue:
app `build.gradle` contains following lines:
>debugCompile project(path: ':sdks:GithubAndroidSdk', configuration: 'debug')
>releaseCompile project(path: ':sdks:GithubAndroidSdk', configuration: 'release')
But the sdks/GitHubAndroidSdk directory is empty so it fails to find the module. I've commented out those 2 lines and it at least started to compile (which obviously fails due to lack of the module).
I tried adding https://github.com/gitskarios/GithubAndroidSdk as submodule but git doesn't allow me, saying sdks/GithubAndroidSdk already exits in index.

**Comment by alorma** [comment]
Did you pull from command line?

Then you need to pull submodules too.

 ```
git submodule init
git submodule update
 ```

After that

 ```
cd sdks/GithubAndroidSdk
git checkout develop
 ```

That should fix your problem

**Comment by arkadiytehgraet** [comment]
Thanks, it solves the issue. Btw, was it documented anywhere or is it considered somewhat obvious? It's my first time trying to contribute to a project that big, so I don't know for sure.

**Comment by alorma** [comment]
It's not docunmented, i will add to Readme.
