### ISSUE TITLE
Is it possible to close issues? 

### ISSUE THREAD

**Issue by Rainer-Lang** [gitskarios/Gitskarios#146]

**Comment by alorma** [comment]
Is possible if you open it from issues list.

If you open from notifictions (or from url), is not possible yet.

**Comment by reyhansofian** [comment]
How to do it? I can't see any close issue  button on issues list

**Comment by alorma** [comment]
Yes, you must enter into issue detail, and then press the three dots,
there's an option to close issue

**Comment by reyhansofian** [comment]
I see. Looks like I didn't have permission to close issue.
