### ISSUE TITLE
Add some options to the timeline

### ISSUE THREAD

**Issue by rocboronat** [gitskarios/Gitskarios#149]
It's great to see all the events from people I follow, but there are too stars. It could be interesting to add an option to hide the event that are only a star, instead of "actual" work like creating a repo, commiting some changes...

**Comment by alorma** [comment]
Something like filtering the event type? So i can check what events i want to see?

**Comment by alorma** [comment]
That feature has been added in last release, hope you find it useful and easy to use

**Comment by rocboronat** [comment]
Thanks @alorma !
