### ISSUE TITLE
The repositories list scroll has an issue

### ISSUE THREAD

**Issue by rocboronat** [gitskarios/Gitskarios#151]
It's not possible to scroll to the end of the list.

![screenshot_2015-07-02-20-18-53](https://cloud.githubusercontent.com/assets/456499/8494092/c361955e-2161-11e5-909f-acadc23fe67d.png)

**Comment by alorma** [comment]
@rocboronat Planned

**Comment by rocboronat** [comment]
:+1:

**Comment by alorma** [comment]
Fixed
