### ISSUE TITLE
Listing repositories you are collaborator of

### ISSUE THREAD

**Issue by claudiodangelis** [gitskarios/Gitskarios#152]
It would be nice to have repositories you are collaborator of listed somewhere, eventually in the "Repositories -> Yours" tab (or maybe a brand new tab?).

Currently, in my understanding, the only place these repositories are listed into is the "Repositories -> Watched & Starred" tabs, which is a bit inconsistent as you can unwatch/unstar a repository and still retain collaborator privileges, not to mention that the more starred repositories you have, the harder it is for you to look them up.

For what is worth, GitHub's website itself doesn't handle this very well either, as you can only find these repositories from the homepage :)

Thanks for this great project,
Claudio

**Comment by alorma** [comment]
:+1:

I like the idea, i need to check if API provides this information

**Comment by alorma** [comment]
It seems that there are no option no get that from API :-1:

**Comment by claudiodangelis** [comment]
By requesting `/user/repos` and setting `type` to "member" you get repositories you are member of (private repos too) and owned by someone else. Maybe you could "merge" the responses?

https://developer.github.com/v3/repos/#list-your-repositories

**Comment by alorma** [comment]
Hey @claudiodangelis .

I upload a new version with contributors repository list.

Can you check if that is what you expect?

Join Crashlyitics to test: https://betas.to/TVbqhdCA

**Comment by claudiodangelis** [comment]
Bernat, it works great!

Claudio d'Angelis

claudiodangelis@gmail.com
Skype: claudiodangelis



2015-07-18 13:17 GMT+02:00 Bernat Borrás Paronella <notifications@github.com

**Comment by alorma** [comment]
OK great!
