### ISSUE TITLE
Create Local Cache of a Repository/Downloaded-Only Mode

### ISSUE THREAD

**Issue by havemeyerd** [gitskarios/Gitskarios#153]
As I understand it, the current download feature just downloads the zip of the repo. It would be cool to also have the option to instead cache the repo (or branch) locally so that you can view it without consuming data.

Additionally, a "Downloaded-only" browsing mode could be implemented for viewing the cached versions of downloaded repos. These repos would be updated when a WiFi connection us established or when "Downloaded-only" mode was excited.

This would be similar to the feature in Google Play Music where you can download a subset of songs to local phone storage.

Would likely be a low priority seeing as source files are pretty small, but if there are additional resources that are checked into the repo files may get larger than kilobytes. Would be less of a concern for data usage, and more of a concern for when I've reached my data cap and my speeds are throttled.

My personal user scenario for this app will be looking over source code as examples on the train for a way to productively pass the time if that helps you understand the suggestion.

**Comment by alorma** [comment]
Hi

That is a cool feature, but i don't have the time for it.

That needs a full refactor of app and how the content is loaded.

If you, or anyone else, wants to start with it and do a PR i will be very happy.
