### ISSUE TITLE
Tabs are not shown when trying to scroll up

### ISSUE THREAD

**Issue by arkadiytehgraet** [gitskarios/Gitskarios#165]
On Lolipop device when I scroll down any list fragment and then try to scroll up, swipe refresh layout tries to refresh instead of scrolling up or it scrolls up but white space is shown instead of tabs. Is this intended?
![Screenshot of refresh instead scroll](http://i.picresize.com/images/2015/07/17/a1y3G.jpg)
![Screenshot of white space instead tabs](http://i.picresize.com/images/2015/07/17/GXPv.jpg)

I'm pretty sure that android.support.design library solves the issue pretty well. Is there any reason not to use it everywhere in the project?

**Comment by alorma** [comment]
In fact, those problems comes from design support library.

Since it's just a beta release of the library, i will rollback with the use of that

**Comment by saulmm** [comment]
@alorma take a look to the new version -> https://plus.google.com/u/0/+AndroidDevelopers/posts/XTtNCPviwpj maybe there are some bug fixes
