### ISSUE TITLE
can not merge pull requests

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#168]
it would be superb if the app could allow merging of pull requests. I can't find the button to push. also it would be great if the app could show notifications from CI and all other checks just like the web interface does today.

**Comment by mmoayyed** [comment]
example https://github.com/Unicon/cas/pull/25

**Comment by alorma** [comment]
What do you mean by

> the app could allow meeting of pull requests

**Comment by mmoayyed** [comment]
Sorry, darn auto complete! meant to say "merging of pull requests"

**Comment by alorma** [comment]
Yes, the app allows to merge repositories if you open them from issues tab.

It not allow if you open from events / notifications / url interceptor.

I will work on it when i finish the PullRequest content issue :grinning:

**Comment by mmoayyed** [comment]
OK, thanks for the update. I'll try from Issues tab and see if I can find the option.

**Comment by mmoayyed** [comment]
OK that worked but it is really inconvenient. I have to find my repo, go to issues and then merge. it would be much easier if I could just click on a PR on my dashboard and select merge. nice and intuitive

**Comment by alorma** [comment]
I plan to add support from anywhere :)

**Comment by alorma** [comment]
I will publish the new version right now

**Comment by mmoayyed** [comment]
Thank you very much!
