### ISSUE TITLE
Can't build project with gradle

### ISSUE THREAD

**Issue by chrjsorg** [gitskarios/Gitskarios#174]
Hi,
Unfortunately I cant build the project within android studio.

    Gradle 'Gitskarios' project refresh failed
    Error:Configuration with name 'debug' not found.

Version info:
Mac OSX 
Android Studio v1.3 RC3
Java Version 1.8.0_51

I'd like to provide some more infos. Let me know if you need anything.

Cheers,
 Chris

**Comment by alorma** [comment]
Hi.

I will update the README today with a full description on how to fork this project.

**Comment by alorma** [comment]
Hi @chrjsorg can you check the FORK guide?

https://github.com/gitskarios/Gitskarios/blob/develop/FORK.md

**Comment by chrjsorg** [comment]
git submodule init && git submodule update did it for me. Thank you!
