### ISSUE TITLE
Last repository not fully shown in repository lists

### ISSUE THREAD

**Issue by gmenih341** [gitskarios/Gitskarios#176]
Under Repositories, Starred and Watched, the last repo is cut in half if the list is too big for screen.

Using LG G3 Android 5.0

**Comment by alorma** [comment]
Which version of the app are you using?

Can you provide also the Git Hash (get it in Settings), thanks!

**Comment by gmenih341** [comment]
Ver: 2.4.8 (2483)
Hash: 38ac806

**Comment by gmenih341** [comment]
Nevermind. I didn't see there was an update. It works now :+1:

**Comment by alorma** [comment]
Good! Thnks for opening issue anyway! :smiley_cat:
