### ISSUE TITLE
Add Find in text

### ISSUE THREAD

**Issue by twendt** [gitskarios/Gitskarios#177]
Thank you for this great app.
Currently all I am missing is a "Find in text" function as I am often studying github repos on my mobile.
It would be really great if you could add that.

**Comment by alorma** [comment]
What you mean by `Find ineText`?

**Comment by twendt** [comment]
When I open a source file in the app, then it is opened with the international viewer. There I would like to be able to search for text within the opened file.

**Comment by alorma** [comment]
Ok.

But that is anything github provides? Or generic ctrl + F?

**Comment by twendt** [comment]
ctrl + F describes it perfectly.
