### ISSUE TITLE
"contributed" not working

### ISSUE THREAD

**Issue by Hauwertlhaufn** [gitskarios/Gitskarios#178]
In the sliding menu "Repositories" nothing is shown on my device at "CONTRIBUTED"
It just says "No membership repositories found" and "RETRY".
Shouldn't there be the "Repositories contributed to" from my profile?
 Best regards

**Comment by alorma** [comment]
It should.

But, as far as i know, API not provide this information.

As example, in website i have 5 repositories as a contributed, and API only provides 1...

**Comment by Hauwertlhaufn** [comment]
Ok, thanks for this information. Hopefully GitHub will fix that in the future...

**Comment by alorma** [comment]
> We don't currently expose that data in the API. However, I'll certainly consider this a feature request and pass it along to the team.

Sorry  :disappointed:

**Comment by mmoayyed** [comment]
Maybe a parallel feature might be to allow the user to "bookmark" certain favored repositories? We star many, but we want to keep track of those we focus on the most. Sound reasonable?

**Comment by alorma** [comment]
There's a watch, that allow you to kept your most important repositories.

**Comment by mmoayyed** [comment]
are you referring to the github feature of watching a repository? That does help; the problem with that however is that you only get notified of activity. There is no easy way to browse to the repo.
