### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by giovannipessiva** [gitskarios/Gitskarios#180]
Emoji codes are not displayed as images in repositories descriptions and commit messages .
It's not a widely used feature, but it could be an improvement :)

**Comment by alorma** [comment]
Commit messages can contain emojis?

**Comment by giovannipessiva** [comment]
yep, check this out: https://github.com/giovannipessiva/l4w/commit/e5dc48478097a87fb7063b522ae57ade554685a0

**Comment by alorma** [comment]
Ok! I will try

**Comment by alorma** [comment]
Done :dancer: 

Available in next release

**Comment by giovannipessiva** [comment]
It doesn't work anymore :crying_cat_face:

**Comment by alorma** [comment]
Hey @giovannipessiva i will replace the old emojis for new ones :)

**Comment by pkramme** [comment]
Close?
