### ISSUE TITLE
v2.5.1 suddenly needs Device ID/call information

### ISSUE THREAD

**Issue by aquatix** [gitskarios/Gitskarios#182]
Hey, I'm loving Gitskarios, but the current update wants a new permission which I find a bit odd and prevents me from upgrading. Where does Gitskarious need my Device ID and/or call information for? (Can't seem to find the relevant commit in the recent history).

Thanks :)

**Comment by alorma** [comment]
Hi.

I'm investigating that, because i not add the `android.permission.READ_PHONE_STATE` permission.

Maybe one of the librarier added itself.

Thankr for this feedback, i will update this issue with more informaton soon.

**Comment by aquatix** [comment]
Cool, thanks!

That explains why I couldn't find it in your updates indeed :)

**Comment by alorma** [comment]
Found where the problem is.

It will be abailavle in a couple of hours
