### ISSUE TITLE
add a pull requests tab

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#184]
I think the issues tab shows all issues and prs. could we perhaps see a way to filter them by type? or add a separate tab for pulls just like GitHub itself does?

thanks for all the hard work. great app!

**Comment by alorma** [comment]
Another tab!

I will try to get that

**Comment by mmoayyed** [comment]
Thank you.

**Comment by mmoayyed** [comment]
please change the title to pull requests, not pull request.
