### ISSUE TITLE
add popular repositories section

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#185]
when I log into GitHub, on the dashboard feed I see a handful of repositories that I contribute to the most. could I see the same set in this app? there is a tab for contributed repositories but it does not match what I see on GitHub.

**Comment by alorma** [comment]
is this a duplicate of https://github.com/gitskarios/Gitskarios/issues/178 ?

**Comment by mmoayyed** [comment]
It is, yes. Thanks for the heads up
