### ISSUE TITLE
duplicate menu items

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#186]
the drop down menu on the events page has duplicate menu items for "support development"

**Comment by mmoayyed** [comment]
browse to repo on push events

**Comment by alorma** [comment]
I can't reproduce that.

Can you explain how you get that? Thanks

**Comment by mmoayyed** [comment]
On the main Events page, click the button in the top right hand corner. The one that looks like 3 dots. Two menu items pop up with "Support Development". I can attach a screenshot if that helps

**Comment by brittneybrinsfield** [comment]
Need my video I can't play none of them
