### ISSUE TITLE
Error on 'Manage Repositories'

### ISSUE THREAD

**Issue by YoshiMad08** [gitskarios/Gitskarios#188]
Having the Manage Repositories page open for over ~3 seconds causes an "Unfortunately, Gitskarios has stopped' message, before returning you to the repo's screen, but blank and with no information but the title at the top. This error is somewhat strange, and is only happening on certain repos. May be hard to reproduce.

Reported from a Samsung Galaxy S3 (i9300) running the latest Unofficial CyanogenMod 12.1 Lollipop ROM.

**Comment by alorma** [comment]
Should be fixed in las release
