### ISSUE TITLE
integration test results in pull requests

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#191]
is it possible to show the status of integration tests for a pull request? like those that are run by Travis CI? if the project already has the right webhooks for Travis, can we show those results?

**Comment by alorma** [comment]
i will take a look in the API

**Comment by alorma** [comment]
Done. You will see that in commits detail screen.

I will update later the PR view, in order to show it

**Comment by alorma** [comment]
Done :dancer:
