### ISSUE TITLE
notifications icon & push notifications

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#192]
if when there are notifications, please change the icon so that it is a bit more noticeable than just red color. 

also,please provide options for push notifications via the native Android intents. should be very helpful. 

thanks again.

**Comment by alorma** [comment]
What do you mean by push notifications via thenative Android intents?

**Comment by mmoayyed** [comment]
I am sorry if I don't have the right terminology. What I meant was, when I get a notification I would want my device to alert me. Similar to how you get notifications for emails, facebook messages, etc. I don't want to go into the app and see if I have some. I want the device to tell me if there is one, and provide options so I can ignore, delete, or reply.

**Comment by mmoayyed** [comment]
P.S I assume that sort of functionality is termed as Push Notifications. and I think Android calls it Intents. Maybe not.

**Comment by alorma** [comment]
Ok i see.

Yo can enable a notification from System Settings -> Accounts -> Gitskarios -> Enable switch.

This will get notifications each 30 minutes (for now), and notify if you have any.

I know it's a bit tricky, i will fix.

**Comment by mmoayyed** [comment]
Excellent. That is very sufficient. Thank you.
