### ISSUE TITLE
Render md documents

### ISSUE THREAD

**Issue by RobDesideri** [gitskarios/Gitskarios#196]
In Android 4.2 device the md documents are not render, it appear a white screen.

**Comment by RobDesideri** [comment]
![](https://www.dropbox.com/s/72373rzxmor9pfg/2015_08_30_13.36.34.png?dl=0)

**Comment by RobDesideri** [comment]
![2015_08_30_13 36 34](https://cloud.githubusercontent.com/assets/11737918/9567059/7f79c5e8-4f1d-11e5-817d-29224d578d44.png)

**Comment by amatkivskiy** [comment]
Same on the Android 5.1.1 (nexus 5).

**Comment by dkniffin** [comment]
:+1:

**Comment by alorma** [comment]
I cannot reproduce this.

Can you provide more information? Is this still happen?

**Comment by RobDesideri** [comment]
Perfect! Thanks very much.
