### ISSUE TITLE
Tabs sometimes get stuck half-visible on profile page, see screenshot

### ISSUE THREAD

**Issue by neilscudder** [gitskarios/Gitskarios#210]
can't seem to attach screenshot

**Comment by alorma** [comment]
Profile page doesn't have tabs.

Can you provide more info?

**Comment by neilscudder** [comment]
Sorry, its the repositories page actually. I just have two repos, and if I scroll down the tabs disappear and I can't get them back. sometimes they get stuck half way. It's a minor glitch.

**Comment by neilscudder** [comment]
I tweeted some screenshots here: https://twitter.com/NeilScudder/status/642799150656950272

once the tabs disappear they can be hard to get back

**Comment by alorma** [comment]
It's a problem with the android support library, i will try to fix it.

PD: you can tweet to @gitskarios user, we are on it :)
