### ISSUE TITLE
More descriptive android notification

### ISSUE THREAD

**Issue by dkniffin** [gitskarios/Gitskarios#212]
Right now, the android notifications simply say "1 Notification". It should display a little bit of details about the notification.

**Comment by alorma** [comment]
![photo_2015-09-14_20-31-04](https://cloud.githubusercontent.com/assets/887462/9858172/7d7a007e-5b1f-11e5-8bdb-0073e9ee3b88.jpg)

**Comment by dkniffin** [comment]
:+1:
