### ISSUE TITLE
allow picture uploads for issues

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#219]
when commenting on issues please allow a way to upload pictures from the device. useful for attaching screenshots

**Comment by alorma** [comment]
Github doesn't provide any API for that.

You can add a image URL, so uploadeyourself to imgur, twitter, dropbox, or similar.

Planned for future

**Comment by mmoayyed** [comment]
Yes, true. Plenty of desktop apps simply allow one to upload the image to some place else like imgur as you said, and they simply paste in the URL.

**Comment by alorma** [comment]
As soon as the API provides that, i will implement
