### ISSUE TITLE
badges don't render on readme

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#220]
I only see picture icons instead the actual badge. u can see this by pulling up this repo via the app

**Comment by alorma** [comment]
Android doesn't provide that functionality.

I will not solve this for now.

**Comment by sils1297** [comment]
FWIW I do see badges when I open the readme as a file, they're only not shown in the overview page. (Plus viewing badges is a major usecase of the overview view.)

**Comment by alorma** [comment]
I know that.

But, for now, i don't have any way to render those badges into overview.
