### ISSUE TITLE
Selecting text in opened documents isn't visually indicated

### ISSUE THREAD

**Issue by sils1297** [gitskarios/Gitskarios#225]
Steps to reproduce:

1. Open a repository
2. Open a document in it.
3. Long press on some word

Expected:

- Word gets selected.

Actual:

At least there's no visual indication of what is selected.

Let me know if you can't reproduce that, then I'll probably have to make a screencast or so.

**Comment by alorma** [comment]
Hi.

Does it still applies?

**Comment by sils1297** [comment]
Still applies to 2.6.8

**Comment by alorma** [comment]
Which android version are you using?

**Comment by sils1297** [comment]
6.0

**Comment by alorma** [comment]
ok.

I see it only works for readme content, and not other contents.
