### ISSUE TITLE
[RFE] Show issue/PR labels

### ISSUE THREAD

**Issue by sils1297** [gitskarios/Gitskarios#226]
this is a really important feature for me because we're using labels a lot for managing our issue/PR workflow

**Comment by alorma** [comment]
You mean in the issues / pr list?

You can see in the detail page for now.

**Comment by sils1297** [comment]
yes in the list. that would greatly help me as labels are great to get an overview over what in the list if actually relevant.

**Comment by alorma** [comment]
Done

**Comment by sils1297** [comment]
Cool, thanks!
