### ISSUE TITLE
[RFE] Mark all notifications as read

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#229]
please provide an option to mark ALL notifications as read, once.

**Comment by miigotu** [comment]
marking all read per repo is not enough? how many different repos are you getting notifications for? xD

**Comment by mmoayyed** [comment]
I have about 6, and each on a daily basis could have 5 notifications. I would rather not press that button 6 times, but once.

**Comment by miigotu** [comment]
@mmoayyed I get over 60 notifications a day, 6+ repos. A few clicks saved is always nice but I don't see this as being a huge difference =P

**Comment by alorma** [comment]
Don't discuss guys! I love you both ;)

I will add this, but it's not a priority right now, there are a lot of improvements and new things comming. I will fix it as soon as i can

**Comment by mmoayyed** [comment]
any updates on this?

**Comment by alorma** [comment]
Yes, i'm workring on it
