### ISSUE TITLE
"bad_verification_code" When Trying to Setup Dev Instance

### ISSUE THREAD

**Issue by mkoch227** [gitskarios/Gitskarios#233]
I'm working on updating my fork of Gitskarios.  I've updated my `gradle.properties` in `~/.gradle/gradle.properties` to:

```
GH_DEV_ID=<application dev id>
GH_DEV_SECRET=<application dev secret>
GH_DEV_CALLBACK=gitskariosgithubdevel://gitskarios

.. same values for GH_PRO_ID, GH_PRO_SECRET, GH_PRO_CALLBACK
```

When running the app on my physical devices, I tap "add account", log into GitHub, and am then redirected to Gitskarios Dev. Then a toast pops up saying "bad_verification_code", and I'm stuck at "Requesting user token".  This happens in both `develop` and `master` (Gitskarios on the Play Store works fine, so I'm pretty sure it's not an issue with the app itself; rather some config issue).  I also tried deleting and recreating the application in GitHub, but I'm still given "bad_verification_code".  Any thoughts?

I'm also not asked to grant access, like I am when I connect using the Play Store version of Gitskarios. Not sure if that's an issue or not.

**Comment by alorma** [comment]
I think is something related to callback url, which one are you using?

**Comment by mkoch227** [comment]
I was just using `gitskariosgithubdevel://gitskarios`, but I then noticed that the URL contained the callback_url being `gitskariosgithubdevel://oauth`. Once I changed my application's callback URL and `GH_DEV_CALLBACK` to `gitskariosgithubdevel://oauth`, everything worked again.  It looks like I must have missed something in `FORK.md` or something :grinning:
