### ISSUE TITLE
RFE: add a section for bookmarked/favorite repositories

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#237]
right now it's difficult to find the repos I care about between watched, contributed, mine and organization tabs. I want a single tab where I can add my favorite repos there and by default the app should switch to that tab so I wouldn't have to jump around.

**Comment by alorma** [comment]
I guess, that's why star / watch are.

If i add a bookmark option, it won't be synced across devices with your account, so why it have sense?

**Comment by mmoayyed** [comment]
Problem with stars is: I star way too many repos but the ones I really want to browse to from time to time are just a few. These are repos that I dont necessarily want to watch either because I dont want to know to know everything that goes on in the repo, but just want to have them handy when I need to. Like this repo here in fact. 

I would be OK with a no-sync option. Fav repos can be added manually per device for now.
