### ISSUE TITLE
Important bug: private to public repo

### ISSUE THREAD

**Issue by fncapps** [gitskarios/Gitskarios#241]
I just discovered a huge bug in the app!

If you are working with a private repository, when you press the overflow icon in the toolbar and press "Manage repository" it will show you the repository settings. Pressing back will turn the repository public without any advise!

Please fix this, I almost had a heart attack 😨
Thanks

**Comment by alorma** [comment]
thanks!

I will fix it

**Comment by alorma** [comment]
Fixed. Thanks fdor reporting it
