### ISSUE TITLE
Github username piled with photo

### ISSUE THREAD

**Issue by dikiaap** [gitskarios/Gitskarios#242]
OS device lolipop

![img](http://i.imgbox.com/rLYrHFC2.png)

**Comment by mikepenz** [comment]
@dikiaap hi. this is an issue by the used **MaterialDrawer** library. What's your screen resolution?

**Comment by alorma** [comment]
Looks it's a problem with Roboto font, as mentioned in mikepenz/MaterialDrawer/issues#751

**Comment by dikiaap** [comment]
Yeah, fix. Version 2.8.4 :+1:
