### ISSUE TITLE
Feature Request: Scroll to bottom of issue..

### ISSUE THREAD

**Issue by miigotu** [gitskarios/Gitskarios#246]
In SiCKRAGETV/sickrage-issues we re-use our issues for re-appearing bugs, and the issues can become quite long with many replies.

It would be nice to have a "scroll to bottom" option instead of having to swipe repetitively for 2 minutes lol

**Comment by alorma** [comment]
u_U OK

I will redesign this screen, and i will add this feature

**Comment by miigotu** [comment]
Sweet thanks, I guess this should work in PR too, although the comments in those are usually less.
