### ISSUE TITLE
Document rendering bug

### ISSUE THREAD

**Issue by neilscudder** [gitskarios/Gitskarios#249]
if I try to open this file (https://github.com/ipfs/node-ipfs-api/blob/master/dist/ipfsapi.js) in gitskarios, it just shows a blank white screen. 

After pressing the back button and continuing to use the app, I find that I can't open any documents from the source tab anymore, in any repo. Restarting the app resets this behaviour.
  
it may be that I am not waiting long enough for the original file to download, thereby interrupting the process by pressing back too early.

**Comment by neilscudder** [comment]
I tried again, waiting 60 seconds, after which it seemed to time out and show some of the document. I could see about 500 limes with a sharp cutoff midline at bottom. app did not crash

**Comment by alorma** [comment]
Thanks, i will check

**Comment by alorma** [comment]
You can, always, open in browser directly.

It's a workaround, i will try to fix this
