### ISSUE TITLE
Back button breaks

### ISSUE THREAD

**Issue by neilscudder** [gitskarios/Gitskarios#250]
it seems that when I open the app after leaving it for a while, the back button will not work. I have had trouble reproducing the behaviour, but I have seen it several times since the last update

**Comment by alorma** [comment]
Which screen?

**Comment by neilscudder** [comment]
Source tab

778-235-8561
www.neilscudder.com
www.playnode.ca

**Comment by alorma** [comment]
I updated the app, is this still happening?

**Comment by neilscudder** [comment]
It looks better. I deep linked from twitter into a repo, and the back
button took me from the file source to the file's repo. I'll test it a bit
more today

778-235-8561
www.neilscudder.com
www.playnode.ca

**Comment by neilscudder** [comment]
I think you can close this issue. I will post another if I can reproduce it again
