### ISSUE TITLE
[request] Native downloader for GitSkarios

### ISSUE THREAD

**Issue by VitaminX4** [gitskarios/Gitskarios#253]
Sometimes the default android downloader just don't work properly. Also, there is no way to pause the download. If GitSkarios had an in app downloader, it'd be easy to keep in track with download, pause it and also download updated source.

**Comment by alorma** [comment]
It's a cdmplicate feature, i will keep this idea in the whishlist.

Thanks

**Comment by VitaminX4** [comment]
Thanks for your reply. And yes. It is complicated. But nothing's ever complicated on GitHub. We figure it out together 😊

Hope we will get that feature soon. Thanks.

**Comment by alorma** [comment]
Pull Requests are very very welcome :b

**Comment by VitaminX4** [comment]
I'm a newbie in programming. Just started learning. I'd have pulled a request if I knew programming. Maybe when I learn, I'll contribute to some projects. For now, I'll brainstorm you with ideas.
