### ISSUE TITLE
Event list item onClick() behavior.

### ISSUE THREAD

**Issue by IvBaranov** [gitskarios/Gitskarios#259]
I use Gitskarios daily, but I still make an attempt to go to user's page by clicking to avatar of user that is responsible for an event.
To move to user's screen I have to search user by name manually.
Do you agree that it is good enhancement? I can create pull request of you like.

**Comment by alorma** [comment]
Yes, this is something i have in my wishlist...

If you make a PR, i will really apreciate it. Thanks!

**Comment by alorma** [comment]
#Fix by #260 

ALready publishen in play store, it will be available in 2 hours aprox.

**Comment by IvBaranov** [comment]
Great!

**Comment by alorma** [comment]
Thanks for your PR
