### ISSUE TITLE
Can't create new issues

### ISSUE THREAD

**Issue by neilscudder** [gitskarios/Gitskarios#261]
After app update today. CAN create comments on existing issues

**Comment by alorma** [comment]
O_o, which repository are you having this problem? Is private? It's inside an organization?

**Comment by neilscudder** [comment]
No, my repo, https://github.com/neilscudder/control

**Comment by alorma** [comment]
Do you let me test on it?

**Comment by neilscudder** [comment]
here is the problem:
1) the new issue button in my own repo does nothing
2) the new issue button in gitskarios repo is absent

the comments functionality is unrelated. you can try to submit an issue to my repo, but I think the button to do so will not appear

**Comment by alorma** [comment]
Ah ok i see what you mean.

I will fix it today, thanks

**Comment by alorma** [comment]
Fixed

**Comment by neilscudder** [comment]
Could you release this? Not being able to create issues is...a real issue
for me

**Comment by alorma** [comment]
Yes, i will release this afternoon.

**Comment by neilscudder** [comment]
Thanks, I really appreciate your work. I am forced to work on a tablet
because of disability.

**Comment by alorma** [comment]
Hi.

I released a new version yesterday. Is everything ok?

**Comment by neilscudder** [comment]
I just checked. It lets me create an issue, but then the issues list is all
screwed up. Instead of putting the new issue at the top, it adds 4 new
whole copies of the whole list at the bottom.

**Comment by alorma** [comment]
Uhm ok... It's supossed that i tested that before publish, but aparently not too welli just saw it.. i will fix it!
