### ISSUE TITLE
HTTP 404 https://api.github.com/user/starred/Behat/Behat

### ISSUE THREAD

**Issue by maoruibin** [gitskarios/Gitskarios#268]
I fork this project and set  personal client、auth info in  AndroidManifest file like this 

       <meta-data
            android:name="com.alorma.github.sdk.client"
            android:value="***************************"/>

        <meta-data
            android:name="com.alorma.github.sdk.secret"
            android:value="***************************"/>

        <meta-data
            android:name="com.alorma.github.sdk.oauth"
            android:value="gitskariosgithubdevel://oauth"/>

in Application 

      GithubDeveloperCredentials.init(new MetaDeveloperCredentialsProvider(this));

and run successfully. but when i open RepoDetailActivity the star icon would not show,and after watch code and debug,I find the question is this 
      
         <--- HTTP 404 https://api.github.com/user/starred/Behat/Behat (266ms)
        Server: GitHub.com
        Date : Fri, 20 Nov 2015 03:28:10 GMT
        Content-Type: application/json; charset=utf-8
         Transfer-Encoding: chunked
        Status: 404 Not Found
        X-RateLimit-Limit: 5000
       X-RateLimit-Remaining: 4907
      X-RateLimit-Reset: 1447991281
      X-OAuth-Scopes: delete_repo, gist, notifications, repo, user
      X-Accepted-OAuth-Scopes: 

it point 404 , please give me some advice ,thanks ~

**Comment by alorma** [comment]
Mmmm

This looks like a private repo, right?

It's inside an organization? If it's, you need to grant access for gitskarios.

Please tell me if this is the problem

**Comment by alorma** [comment]
Please, can you check the GithubAndroidSdk alone(in new project)eand check if this happens?

 If so, please add a new issue there

https://github.com/gitskarios/GithubAndroidSdk

**Comment by maoruibin** [comment]
year,it is a private repo,and not inside an organization , and now  grant access is not a problem .
 Let me check GithubAndroidSdk soon~

**Comment by maoruibin** [comment]
now even use your apk file , it also can't execute star or watch action, It may be a net problem or other problem ,let me close this issue first .
