### ISSUE TITLE
Feature request: news

### ISSUE THREAD

**Issue by petobens** [gitskarios/Gitskarios#270]
Is it possible to add a news section? One of the things that I like about the ForkHub app is precisely its news section. It would be really cool if Gitskarios (which I find way better in general to ForkHub) also had one.

Thanks in advance!

**Comment by alorma** [comment]
HI @petobens 

What's exactly the `news` section? Is not the same as `Events` section in Gitskarios?

**Comment by petobens** [comment]
I think it is different to the `Events` section. Basically in any repository I can see its recent activity:

![screenshot_20151121-152408](https://cloud.githubusercontent.com/assets/2583971/11319905/adee5292-9066-11e5-8b33-d2d762c4fd5a.png)

**Comment by alorma** [comment]
Ah ok, you  mean repository news.

I will check, thanks

**Comment by petobens** [comment]
Thank you!
