### ISSUE TITLE
Star repo feature is broken

### ISSUE THREAD

**Issue by cmc00022** [gitskarios/Gitskarios#271]
As you can see in the attached image the stars icon does not appear and nothing happens when I click on it (expecting to add/remove a star on the current repo)

![screenshot_20151121-214841](https://cloud.githubusercontent.com/assets/3494156/11320717/be9f6b24-909a-11e5-8c67-418da32c9dd2.png)

**Comment by alorma** [comment]
Fixed in latest release.

Can you confirm?

**Comment by cmc00022** [comment]
Seems to work fine now. 

It might be part of a new issue, but when I star the repo the icon become blue, but it does not go back to grey when I unstar it (which kind of let the user not knowing what happened)

The same happens with the watch option.

**Comment by alorma** [comment]
Fixed
