### ISSUE TITLE
Enterprise login fails without https url prefix

### ISSUE THREAD

**Issue by Sloy** [gitskarios/Gitskarios#273]
When loggin in GitHub Enterprise, the url must have the https prefix, otherwise the login fails without any message. 

Example: `https://github.mycompany.com` works, but `github.mycompany.com` doesn't.

It would be better if a) Gitskarios tried default protocol or b) it shows a validation error saying you must add the protocol prefix.

Thanks!

**Comment by alorma** [comment]
Fixed
