### ISSUE TITLE
Watched Repositories Circulates

### ISSUE THREAD

**Issue by S--Minecraft** [gitskarios/Gitskarios#274]
When scrolling down and loads more repositories, the repositories are duplicated with the loaded repositories.

**Comment by alorma** [comment]
Oh, thnt only happen on watched repositories.

Thanks i will check

**Comment by S--Minecraft** [comment]
Yes it only happens on watched repositories.
Thanks.

**Comment by alorma** [comment]
Fixed

**Comment by S--Minecraft** [comment]
Thanks!
