### ISSUE TITLE
lost viewstate 

### ISSUE THREAD

**Issue by jmue** [gitskarios/Gitskarios#278]
Steps to reproduce:
- Start APP, events view is shown
- switch to Repos, starred
- change orientation from portrait to landscape

Result:
- event view is shown

expected:
- Starred Repos view is shown

**Comment by passcod** [comment]
Related to orientation change, but much more annoying:
1. Create an issue
2. Add some body text
3. "Save" body text
4. Change orientation
5. Body text **disappears**
