### ISSUE TITLE
Enterprise wording error

### ISSUE THREAD

**Issue by miigotu** [gitskarios/Gitskarios#283]
Event feed in Gitskarios Enterprise tells me that "medariox created repository SickRage/SickRage 15 minutes ago"
Of course this freaked me out thinking that our 7k commit repository with 10k autoupdating users got deleted somehow.

Checking github, as you can see below, he merely create a branch.

![screenshot_2015-11-27-01-58-49](https://cloud.githubusercontent.com/assets/390379/11438586/ac72a376-94aa-11e5-9220-4499932f1ac9.png)
![screenshot from 2015-11-27 01 59 02](https://cloud.githubusercontent.com/assets/390379/11438589/b22c85b6-94aa-11e5-8c92-e106ea3f227c.png)

**Comment by ghost** [comment]
Hi.

Sorry for that, enterprise version is just a  beta, you know

this is already fixed, i will update a version in a  couple of minutes

**Comment by miigotu** [comment]
@bernatborrasscm no big deal, just didnt know how else to let you know in case you didnt see it yet =P
