### ISSUE TITLE
After closing a file it goes back to repo root

### ISSUE THREAD

**Issue by randombyte-developer** [gitskarios/Gitskarios#284]
Steps to reproduce:
- open a repository in app
- go to file tree tab
- go at least one folder deep
- open a file
- go back with back button or back button in toolbar

Expected result: your are in the same folder as before opening the file

Result: (after automatic refreshing?) you are in the root of the repo

**Comment by jvandenbroek** [comment]
Agreed, love this app, but this is annoying.

**Comment by Khitiara** [comment]
Same issue.

**Comment by Rainer-Lang** [comment]
Same here

**Comment by alorma** [comment]
Ok.

I will try to fix it soon.

**Comment by alorma** [comment]
Fixed
