### ISSUE TITLE
Android notifications stays disabled

### ISSUE THREAD

**Issue by voidzero** [gitskarios/Gitskarios#285]
Heya, love the app. Bit since a few versions ago, the notifications option is no longer working for me. Under Android's Accounts, gitskarios is listed, but has no option to enable/disable. And when I enable notifications in the app itself, the next time I launch Gitskarios, the toggle is just set to disabled again. So I don't get the notifications anymore..

**Comment by mSobhy90** [comment]
Happens to me as well, please fix

**Comment by alorma** [comment]
Going to fix it today

**Comment by mSobhy90** [comment]
Thanks man, awesome work on the app 👍

**Comment by alorma** [comment]
Fixed

**Comment by voidzero** [comment]
Thank you! Marvellous.

**Comment by mSobhy90** [comment]
:+1:
