### ISSUE TITLE
Notifications: Participating

### ISSUE THREAD

**Issue by xcambar** [gitskarios/Gitskarios#292]
Hi,
Let's start with a thank you: I'm getting used to gitSkarios, and I love it!

The thing I miss though is the "Participating" filter in github, as available here: https://github.com/notifications/participating

I usually have a number of notifications (all, not only participating) but as is, the list of notifications and the count badge mostly are irrelevant to me as I have to go through all of them without even knowing if I was mentioned or has already posted something on a particular thread.

What do you think? Maybe did I miss something in the app?

**Comment by alorma** [comment]
Sounds interasting.

I will check if the api supports it.

**Comment by alorma** [comment]
Wuhu! It looks like the api supports it:

https://developer.github.com/v3/activity/notifications/#list-your-notifications

So i will add it soon, thanks

**Comment by xcambar** [comment]
Ha ha, I was about to post the URL, you beat me to it :wink: 

> So i will add it soon, thanks

Fantastic!
