### ISSUE TITLE
Request: Show References in issues. 

### ISSUE THREAD

**Issue by cbrst** [gitskarios/Gitskarios#293]
A great feature of github issues are the small notifications in the thread when an issue referenced from another issue/repo/PR. It would be great to have them show in Gitskarios as well.

**Comment by alorma** [comment]
Ok. Just tested and is not showed.

I missed something at time gitskarios load the issue.

I will fix it, thanks

**Comment by alorma** [comment]
Sadly, the API doesn't provide this information, so i can't add this to Gitskarios.

If it changes i will add :D
