### ISSUE TITLE
PR labels are not shown

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#298]
pull requests similar to issues can also have labels. they are not shown.

**Comment by alorma** [comment]
Uhmmmm

I see labels in my pull request

Please, provide a link of PR that doesn't display labels
![device-2015-12-21-220042](https://cloud.githubusercontent.com/assets/887462/11941228/54b67fda-a82e-11e5-95ea-f5a1b9c38343.png)

**Comment by mmoayyed** [comment]
I should clarify.

On the main view where icons are shown in a tabbed format, if I click on issues, I see a list of issues with their tags right in the main view. If I click on the PRs icon, I see a list of PRs without their tags. If I click on a PR, I see the tags for the individual PR. 

What I want is to see tags in the main list of all PRs. Similar to Github itself.

**Comment by mmoayyed** [comment]
See https://github.com/Jasig/cas/pulls

**Comment by alorma** [comment]
Mmmm

I see that labels are not shown in the list, but in the detail it's ok

**Comment by alorma** [comment]
Ok i check the api, and it doesn't provide that information.

I will not show it for now, sorry

**Comment by mmoayyed** [comment]
no problem. thanks for checking.

I am setting up a dev environment. hopefully I will be able to contribute soon. I am a perfect noob when it comes to android dev, so please be patient with me :)
