### ISSUE TITLE
badges in Readme don't render

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#299]
I loaded a repo in forkhub. all badges rendered fine. I loaded the same repo via this app. badges do not render. I thought this was an api issue but clearly it can be done.

**Comment by alorma** [comment]
Well...

They uses a webview to load that, and not gitskarios.

I'm looking for a solution

**Comment by alorma** [comment]
I decided to move to a Webview again, hope it fixes

**Comment by mmoayyed** [comment]
Excellent. 

By the way, how can I contribute to the project? are there guidelines? how do I set up the development environment? I would like to start with Android development, and this project feels like it's got legs for a good start :)

**Comment by alorma** [comment]
Hi.

There's a contributing page (CONTRIBUTING.md) with some hints about setup enviornment.

I will update this guide later today, so keep updated :)

About code style... i don't have a specific rules, just the default that Android Studio provides. Gitskarios is a big mix of libraries, architectures, etc, so be polite and that's all

**Comment by alorma** [comment]
Start with open issues, so you will be familiar with gitskarios code

**Comment by mmoayyed** [comment]
Perfect. Thank you.
