### ISSUE TITLE
Sort option for Repositories

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#302]
In the Repositories view, I have a number of repos listed and grouped. Watched, Yours, etc. I would want to be able to set sort options so that the entries in these groups are ordered in a particular way. I don't need one sort option per group. Just one sort option for all.

Options should be:
1. Last updated/pushed
2. Alphabetically
3. Number of stars

**Comment by mmoayyed** [comment]
I noticed this is already available. Thank you. Could you also add "Number of stars" to the options?

**Comment by alorma** [comment]
I have to check if the api supports that
