### ISSUE TITLE
New comments on issues are not shown

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#307]
When I try to post comments on an issue and when I press submit the comment is saved but its not immediately shown unless I  explicitly refresh the screen

**Comment by alorma** [comment]
What version? I fixed that

**Comment by mmoayyed** [comment]
Did an update last night, and that's when I started to notice this. I am always on the latest version. I'll try to duplicate it again.

**Comment by alorma** [comment]
Reopen if is the case
