### ISSUE TITLE
Feature Request: Contributions chart

### ISSUE THREAD

**Issue by farbodsz** [gitskarios/Gitskarios#311]
Much like there is a contributions chart on your profile page on the GitHub website, showing with green squares with various shades the number of contributions you made each day over the course of the past year, it would be wonderful to have the same feature on this app.

The UI wouldn't have to match exactly but it would be a visual representation of the user's contributions.

**Comment by alorma** [comment]
This is in my roadmap ;)

Meanwhile, you can use https://play.google.com/store/apps/details?id=by.aleks.ghcwidget

**Comment by farbodsz** [comment]
@alorma I notice that you've closed this issue.

I was wondering: has it been added or have you decided not to implement it?

**Comment by alorma** [comment]
I decided to close all old issues, since i can't manage all of them, and most are already resolved.

If there's something important, users will reopen the issue, if you want, please reopen it

**Comment by farbodsz** [comment]
@alorma 

That's fair enough - thanks for letting me know. I don't think this is so important that it needs to be reopened at the moment.
