### ISSUE TITLE
Unable to use app

### ISSUE THREAD

**Issue by calebeby** [gitskarios/Gitskarios#317]
As soon as I open the app, all I see is:
![http://i.imgur.com/2LZdmsl.png](http://i.imgur.com/2LZdmsl.png)

**Comment by alorma** [comment]
Hi.

What's your device?

**Comment by calebeby** [comment]
LGL34C

**Comment by AzureMarker** [comment]
I can confirm this on my lgl34c. Same screen.

**Comment by Mcat12** [comment]
Was this fixed?

**Comment by calebeby** [comment]
Yes, it works now. Thanks!

**Comment by AzureMarker** [comment]
Works over here too! :)
