### ISSUE TITLE
@ mentions and replies 

### ISSUE THREAD

**Issue by rocketinventor** [gitskarios/Gitskarios#321]
For issue tracking and other areas areas in github where there are comments, we should be able to reply to a comment or @ mention people. Once the "@" symbol is typed, it should begin searching through the names of people in the thread, then people we follow and finally, all people if there are no matches. Also the mentioned person's name should be bold.

**Comment by alorma** [comment]
That's a huge feature, and not simple to add.

I think its enough to add a button (bottom?) to search users?

**Comment by rocketinventor** [comment]
Update: I think github on desktop just lists a few contributors, then searches the directory if anything more is typed so it shouldn't be as complex to add as initially described.

The behaviour I described is common across twitter, google+, and github desktop so I think different behaviour for mentioning people would be weird and might confuse people. I understand that it might be hard to add but I think it should be added as a long term goal to get the behaviour right.

In the near term, however, if we could long press to "reply" to a message and gitskarios would just insert "@" plus the username in plaintext at the beginning of the draft it would still be quite useful.

P.s. Really good work on the app so far!

**Comment by alorma** [comment]
Yes i know that pattern, the problem is with implementation of that. Is not easy.

I will add the reply option (with replied comment as note?)

I will think on @ think, thanks

**Comment by rocketinventor** [comment]
@alorma No, I don't think there is any need to quote the original message, if that is what you mean.
Thanks for considering!

**Comment by alorma** [comment]
Testing

@rocketinventor

Mentioned from app

**Comment by alorma** [comment]
Next test

@rocketinventor

**Comment by mikepenz** [comment]
@alorma awesome :)

**Comment by rocketinventor** [comment]
@alorma Cool!
