### ISSUE TITLE
ReStructured Text

### ISSUE THREAD

**Issue by xcambar** [gitskarios/Gitskarios#324]
Hi, and happy new year! All the best for your projects!

I see more and more projects with a `README.rst` file and it unfortunately, GitSkarios does not output a formatted version of the description of these projects.

In order to provide a similar experience than Github, do you think it would make sense to parse RST files as it is the case with Markdown files?

**Comment by alorma** [comment]
Hi.

Could yo provide an example?

**Comment by xcambar** [comment]
Sure: https://github.com/dbcli/pgcli

**Comment by alorma** [comment]
Only problem is the images tag.

But other tags are now loaded correctly
