### ISSUE TITLE
Better visibility for commit and pull request status (test results) 

### ISSUE THREAD

**Issue by stgraber** [gitskarios/Gitskarios#326]
Hi, 

First of all, great app, thanks! 

The only difficulty I have with using your app for my work is that it doesn't surface test results in a very useful way. 

I can't easily see from the pull request view if something passed automated testing (travis and two Jenkins texts). 
I can get the information by going to the latest commit and getting the status from there but it's not ideal. 

Any chance the app can be updated to show me something similar to the website? that is, show the status of the last commit right next to the merge button and tell me what tests are mandatory. 

Thanks for the great app!

**Comment by alorma** [comment]
Sure.

That's something i want to change also.

I will update it soon. :)

**Comment by ishitatsuyuki** [comment]
Bump: currently gitskarios ignores the status check for PR.
This is quite unsafe since it can silently do a force-merge without any confirmation.
