### ISSUE TITLE
Submodules do not work

### ISSUE THREAD

**Issue by SuicSoft** [gitskarios/Gitskarios#328]
When I click a submodules it goes to a blank screen

**Comment by SuicSoft** [comment]
Do I have to build it from source. Right now on my Android I have the Play
Store version

On Tue, Jan 12, 2016, 1:23 AM Bernat Borrás Paronella <
notifications@github.com> wrote:

> Closed #328 https://github.com/gitskarios/Gitskarios/issues/328 via
> 010956e
> https://github.com/gitskarios/Gitskarios/commit/010956eae8c89d809bdfc8010370372d2a77df18
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gitskarios/Gitskarios/issues/328#event-511546972.
> 
> ## 
> 
> The Studio/Software Dog,
> Suici Doga

Sent from Inbox by Gmail

**Comment by alorma** [comment]
No @suicsoft.

I published this version to Play Store also 2.7.9
