### ISSUE TITLE
Material zoom icon

### ISSUE THREAD

**Issue by dikiaap** [gitskarios/Gitskarios#333]
I read code with Gitskarios. But in there, i will zoom and found zoom in/out icon like android 2.x version.
u will change?

**Comment by pcjl** [comment]
Pretty sure it's because Gitskarios is using webview to view files, which includes the zoom buttons.

**Comment by alorma** [comment]
Exactly @pcjl

I will try to change those ugly icons

**Comment by dikiaap** [comment]
@alorma Ok, I'll wait that. keep create beautiful art.
