### ISSUE TITLE
Duplicate data on refresh for Gists

### ISSUE THREAD

**Issue by michaelcarrano** [gitskarios/Gitskarios#337]
I noticed that if I refresh (pull down to refresh) that Gists will have duplicate data. 

I also think this happens on Events but my events stream is pretty long right now so not easy to tell if refreshing duplicates that data.

Here's a quick video demonstrating the Gists issue: https://youtu.be/tqj0gHXKqDo

This occurs in v2.8.0

**Comment by alorma** [comment]
Hi

Thanks, yes that happen on Events also. It's a known bug.

I will fix it as soon as possible
