### ISSUE TITLE
Viewing a profiles repos duplicates organisation information 

### ISSUE THREAD

**Issue by andrewcartwright1** [gitskarios/Gitskarios#339]
Hi, just a bug report. 

If you view a person's profile, click organisation then press back to go to there profile the organisation and repo information will duplicate. 

This also happens when viewing a repo from that profile and pressing back.

**Comment by adriancampos** [comment]
It seems to be every time the screen refreshes, too (turning the screen off and on, opening recent apps, etc...). 
Here's a video: https://goo.gl/photos/dmWD3qdzGQgYG4XW7
