### ISSUE TITLE
Repos contributing to shows as empty

### ISSUE THREAD

**Issue by farbodsz** [gitskarios/Gitskarios#341]
The repositories I contribute to (as I see on my GitHub profile on the website) do not appear on this app, and it displays a message saying that there were no contributing repositories found.

**Comment by alorma** [comment]
Are those repositories under a organization? If it's, then you need to approve gitskarios for that organization

**Comment by farbodsz** [comment]
@alorma ,

No, they are not under an organization. I would expect to see the contributions that I see [here](https://github.com/FarbodSalamat-Zadeh) on the app page.

Am I misunderstanding the feature?

**Comment by alorma** [comment]
Fixed!

I will upload a version tonight, please tell me if works or not

**Comment by farbodsz** [comment]
@alorma That was a quick fix - thanks.

I'll let you know once I've received the update.

**Comment by alorma** [comment]
I'm testing it.

And it's not really what is expected :s

I asked github team, because i don't see in the api a endpoint for it

**Comment by alorma** [comment]
Unfortunelly:

> Hi Bernat,
> 
> Thanks for getting in touch! We don't currently > offer that data in the API. However, I'll certainly > consider this a feature request.
> 
> Cheers

**Comment by alorma** [comment]
I will disable that page until api providesethe information

**Comment by farbodsz** [comment]
@alorma Thank you - it's a shame that this feature isn't already available in the API.
