### ISSUE TITLE
Changing device orientation brings you to the 'Events' section and other problems

### ISSUE THREAD

**Issue by geomih** [gitskarios/Gitskarios#343]
When I change the orientation of the device many problems occur to different sections of the app.
- From the sections 'Repositories', 'People & Organizations' and 'Support developement' changing the orientation of the device will load the 'Events' section.
- In the 'Events' section (as well as many other sections) changing the device orientation reloads the section.
- In the 'Invite friends' section, the dialog to choose an account pops up every time I change the device orientation. You can reproduce that by not choosing an account, changing the device orientation many times and then canceling the dialogs.

I think that many of these problems can be solved by adding:
`android:configChanges="keyboardHidden|orientation|screenSize"`
in the manifest file in every `<activity>` that has this problem.
[Relevant information in developer.android.com](https://developer.android.com/guide/topics/resources/runtime-changes.html#HandlingTheChange)

**Comment by alorma** [comment]
Keep orientation in the manifest doesn't really solve the problem.

I just take care of save and restored instances for that.

I will take a look in it, but feel free to contribute if you want

Thanks

**Comment by geomih** [comment]
I'm not suggesting that you keep the orientation of the app fixed if that's what you mean.
The code that I gave you will simply stop reloading the activity when the orientation of the device changes.

I'm really busy this month but I'll try contribute if I find the time.

**Comment by alorma** [comment]
No i don't suggest to keep the orientation _fixed_

What i mean with that, is the app should take care of rotation with `onSaveInstanceState()` and `onRestoreInstanceState()`
