### ISSUE TITLE
Can't comment

### ISSUE THREAD

**Issue by AzureMarker** [gitskarios/Gitskarios#344]
I'm using gitskarios on a Nexus 7 running cm13.
When I try to submit a comment, it doesn't make the comment.

**Comment by webknjaz** [comment]
I'm experiencing the same issue.
CyanogenOS (CM 12.1)

This happens only in repositories in one of my organizations. Interesting fact is that this organization isn't listed in list of my organizations in gitskarios :(

**Comment by AzureMarker** [comment]
Mine is also in an organization.

**Comment by alorma** [comment]
mmmm

did you granted permissions for gitskarios to use this application?

Github changed how permissions are granted, and now it's not by default.

At your org settings you can allow gitskarios to access those information, can you please test it?

**Comment by AzureMarker** [comment]
It works now, thanks for such a nice app!

**Comment by webknjaz** [comment]
I didn't grant permissions to use this organization. Still it's a public org and shouldn't restrict issue commenting/creation to anyone.

**Comment by alorma** [comment]
You mentioned it.

It shouldn't, but organizations block apps by default.

Please, tell me which org is it and i will test

**Comment by webknjaz** [comment]
https://github.com/itkpi

**Comment by webknjaz** [comment]
P.S. I've posted my first comment to this issue from app. And it works. I'm even not a member of this organization.

**Comment by webknjaz** [comment]
According to API docs, it should be possible to create issue for `with pull access to a repository can create an issue`:
https://developer.github.com/v3/issues/#create-an-issue
and list `public memberships, regardless of authentication`:
https://developer.github.com/v3/orgs/#list-user-organizations

For now none of these work.
