### ISSUE TITLE
People & Organizations view persists in the background

### ISSUE THREAD

**Issue by geomih** [gitskarios/Gitskarios#349]
Steps to reproduce:
1. Go from Events to People & Organizations
2. Go from People & Organizations to Events
3. Go from Events to People & Organizations
4. Press the back button from the navigation bar

The problem persists throughout other parts of the app.

![screenshot_20160206-175200](https://cloud.githubusercontent.com/assets/5839115/12867712/76ac4284-ccfd-11e5-964c-7748ba28356d.png)
![screenshot_20160206-175143](https://cloud.githubusercontent.com/assets/5839115/12867714/76b429a4-ccfd-11e5-94e9-1a69c7ae9cc4.png)
![screenshot_20160206-180403](https://cloud.githubusercontent.com/assets/5839115/12867713/76b3810c-ccfd-11e5-9b35-925738f7552c.png)

**Comment by alorma** [comment]
I detected this today.

I will fix it soon, thanks

**Comment by geomih** [comment]
Great. You're welcome!
