### ISSUE TITLE
Creating new repository problems

### ISSUE THREAD

**Issue by geomih** [gitskarios/Gitskarios#352]
- [x] When I create a new repository the 'Add gitignore' option is slightly covered from the 'CREATE' button. Device: Nexus 5, Stock Android 6.0.1
- [x] Adding a value to the 'Description' field doesn't work but after creating the repo I can add a description from the 'Manage repository' option.
- [ ] Lastly, shouldn't the fields Description and Homepage URL be visible when I visit a repo's main page?

![screenshot_20160211-083146](https://cloud.githubusercontent.com/assets/5839115/12983335/8a7d6bb0-d0f1-11e5-82d4-3f465cdd4f64.png)

**Comment by alorma** [comment]
I fixed the first 2 points.

The last one, needs to wait, i have to rewrite all repository overview, so this information will be visible

**Comment by geomih** [comment]
Great!
