### ISSUE TITLE
Editing description of repository shows <githubroot>-Tag

### ISSUE THREAD

**Issue by MDXDave** [gitskarios/Gitskarios#354]
![screenshot_2016-02-15-14-50-32](https://cloud.githubusercontent.com/assets/6099976/13050446/adaf5abc-d3f3-11e5-97ca-80eec5d17f70.jpg)

**Comment by alorma** [comment]
can you please show a

**Comment by alorma** [comment]
It's strange.

Looks like github changed something, i will check it

**Comment by webknjaz** [comment]
Same for me
