### ISSUE TITLE
Seeing Raw HTML When Editing Issue Description

### ISSUE THREAD

**Issue by rummik** [gitskarios/Gitskarios#362]
**_1 Upvote**_ Reproduction steps:
- Open an issue
- Edit the issue description after saving

https://goo.gl/photos/JW4ChkCV65gJuTsJ7

**Comment by ghost** [comment]
This is odd. I'm not getting this issue.

**Comment by TheZoker** [comment]
+1 Same here!

**Comment by TheZoker** [comment]
Same as #354
