### ISSUE TITLE
Push notification does not work

### ISSUE THREAD

**Issue by CPlusPlus17** [gitskarios/Gitskarios#363]
Hello,

I tested both versions (free and enterprise) but in both I don't get any notification information.

I'm using android 6.0.1 stock nexus 5x version. Double checked all permissions and settings. 

Greets
Manuel

**Comment by alorma** [comment]
Those are not push notifications, just checks every 30 minutes.

I'm re-implementing notifications

**Comment by alorma** [comment]
I'd added a  new push notifications system, i will release it soon

**Comment by CPlusPlus17** [comment]
Cool, thanks a lot! :)

**Comment by alorma** [comment]
Hi Manuel.

I published it, if you want to test it, please download the beta :)
