### ISSUE TITLE
Allow issue operations if the user has permission

### ISSUE THREAD

**Issue by ishitatsuyuki** [gitskarios/Gitskarios#376]
Currently any issue that isn't opened from repository view (e.g. notifications/URLs) doesn't let me close it. I'm mostly working on organization, so it will be good if I can modify the issue when I have the permission.

**Comment by alorma** [comment]
That's what i did some time ago, but recently i detected it doesn't work, i will fix asap

Thanks

**Comment by GitskariosTest** [comment]
Fixed, it will be available in the next version

**Comment by alorma** [comment]
Fixed, will be available in the next release
