### ISSUE TITLE
Notifications history

### ISSUE THREAD

**Issue by arieljannai** [gitskarios/Gitskarios#378]
**Feature:**
Save notifications history.
Is it possible to do so? GitHub is not saving the notifications history for an unclear reason (at least unclear for me).
I'd like to be able to see/search/go through notifications from months ago.

What do you think?

_Great app by the way, it really improved on the last year :muscle: :sunglasses:
`In the past I had to use 3 apps in order to get some useful functionality with github, now almost everything is here!`:smile:_

**Comment by alorma** [comment]
HI.

Is the same as: https://github.com/notifications?all=1 ?

**Comment by arieljannai** [comment]
Nope, the all notifications page only shows the last few notifications, or from the last time.

There's no option to see notifications from month or two ago :(

**Comment by alorma** [comment]
No it doesn't look this option exist

**Comment by arieljannai** [comment]
Is it reasonable to save them locally or something? (if the user allow it, of course)

**Comment by alorma** [comment]
Will you be interested in save just a few of them? Or all of them?

All of them is not possible

**Comment by alorma** [comment]
I've published a new version 2.9.4 with support for 'All notifications' as shown in notifications page at Github.com,
