### ISSUE TITLE
Updating my gists page duplicates gist entries

### ISSUE THREAD

**Issue by droped** [gitskarios/Gitskarios#380]

**Comment by farbodsz** [comment]
Is this similar to #403 ?

**Comment by alorma** [comment]
I think it's related.

Can you merge all `duplicate` issues into one?

**Comment by farbodsz** [comment]
Sure. Is there a particular way to "merge" issues on GitHub, or do you want me to create a new issue?

**Comment by alorma** [comment]
Nop, a New issue :$ referencing other ones with #Num

**Comment by farbodsz** [comment]
Thanks @alorma .

I have done so, as you can see in the reference above.

**Comment by droped** [comment]
Sorry for the late response but yes, it is related. Actually, it is the same bug.

**Comment by farbodsz** [comment]
No problem, @poutros. 

See the new issue I've opened as a continuation (which is actually resolved now).
