### ISSUE TITLE
Chips views on adding labels to issues

### ISSUE THREAD

**Issue by alxsimo** [gitskarios/Gitskarios#382]
_Issue:_ Chips views on adding labels to issues
It would be very nice looking to add material design chips, when adding labels to issues.
Check the demo bellow :smiley: 

> App version
> 
> Git build hash from settings:
> 
> Device
> 
> Device android version

_Steps to reproduce:_

_Crash (optional):_

_Screenshots_
![image](https://cloud.githubusercontent.com/assets/579465/14233040/679910f0-f9bd-11e5-96ac-48b6aa034d2d.png)

**Comment by alorma** [comment]
Done at 50% 

I will add a (X) soon

**Comment by Rainer-Lang** [comment]
@alorma Could you help me and point me to the class where the chips are implemented?

**Comment by alorma** [comment]
LabelView

**Comment by Rainer-Lang** [comment]
@alorma Thanks.
