### ISSUE TITLE
Add padding and line break to the project description 

### ISSUE THREAD

**Issue by TheZoker** [gitskarios/Gitskarios#384]
Currently there is no padding for the project (repo) description and also there are no line breaks. In issues this works well.

**Comment by alorma** [comment]
where do you mean there's no line breaks nor padding? Screenshot?

**Comment by TheZoker** [comment]
Here you go:

![](http://fs5.directupload.net/images/160405/tcuoezq5.jpg)

**Comment by alorma** [comment]
Ok thanks
