### ISSUE TITLE
Add button to unsubscribe from issue

### ISSUE THREAD

**Issue by TheZoker** [gitskarios/Gitskarios#385]
This button is missing in issue detail view

**Comment by alorma** [comment]
I know

But is not possible to add it, because api don't provide this feature, unless they've added something new in the las months

**Comment by TheZoker** [comment]
Did you contact the github support and asked them to add it?

**Comment by alorma** [comment]
Of course i did, and their answer was: `we will add it to backlog`

**Comment by TheZoker** [comment]
I will also write them, maybe that will make the progress faster.

**Comment by alorma** [comment]
Thanks then!
