### ISSUE TITLE
App crashes when trying to open huge issue

### ISSUE THREAD

**Issue by TheZoker** [gitskarios/Gitskarios#386]
Here is the log:
http://pastebin.com/3JWWY2rK﻿

Issue is this one https://goo.gl/iz7BIl

**Comment by alorma** [comment]
Sorry, log removed?

**Comment by TheZoker** [comment]
Sorry, I don't know why it was deleted. I tried to get the log again, but the app doesn't crash now. It only shows the loading animation (I waited for like 10 min, but still only the loading animation). 
Did you try to go to that link? Did it open?

**Comment by alorma** [comment]
Nop, i will check why
