### ISSUE TITLE
Improve pull request view 

### ISSUE THREAD

**Issue by TheZoker** [gitskarios/Gitskarios#388]
The color of the footer bar is Grey at the beginning, I have to touch one of the icons, so it gets blue. 

Also the counter has the wrong width. A click on any of the icons changes that. 

When I'm on the most right icons, the counter of the one next to that is aligned wrong. 

![](http://fs5.directupload.net/images/160405/i8r535fm.png)

![](http://fs5.directupload.net/images/160405/tkdshbbd.png)

**Comment by alorma** [comment]
I know this bugs.

I need to update the library that i'm using for bottom tabs

Thank
