### ISSUE TITLE
Issue rename activity has redundant information

### ISSUE THREAD

**Issue by TheZoker** [gitskarios/Gitskarios#390]
**_1 Upvote**_ When some one renames an issue, the username is displayed twice. 
Would be better to add the old and the new title there. 

![](http://fs5.directupload.net/images/160405/u6hqroj5.png)

**Comment by alorma** [comment]
:+1:

Hey, are you able to make some PR's? Will be really great!

**Comment by alorma** [comment]
:+1:

Hey, are you able to make some PR's? Will be really great!

**Comment by TheZoker** [comment]
Will try :)

**Comment by alorma** [comment]
Done :)
