### ISSUE TITLE
User profile pictures flicker on PR assigned page 

### ISSUE THREAD

**Issue by TheZoker** [gitskarios/Gitskarios#391]
When I'm on the pull request page and on the "info" tab and then click on "assigned", the profile picture flicker for some reason. 
(can't provide a Screenshot for that, hopefully you can reproduce it)

**Comment by alorma** [comment]
Yes it's a known bug, it happens also in all other pictures :s

**Comment by TheZoker** [comment]
Really? Not for me :P
