### ISSUE TITLE
Add support for teslaunread-api 

### ISSUE THREAD

**Issue by TheZoker** [gitskarios/Gitskarios#395]
See here: http://novalauncher.com/teslaunread-api/

**Comment by alorma** [comment]
Will try

**Comment by TheZoker** [comment]
So did you add this?

**Comment by alorma** [comment]
Please, read https://github.com/gitskarios/Gitskarios/issues/401

**Comment by alorma** [comment]
And...

I had been thinking on this.

The problem i see with it, is the multiaccount support. How i will display those?
