### ISSUE TITLE
Commit diffs overlaps toolbar

### ISSUE THREAD

**Issue by MDXDave** [gitskarios/Gitskarios#402]
![](http://i.imgur.com/r9qYho9.png)

**Comment by alorma** [comment]
Do you have a commit where i can test?

**Comment by MDXDave** [comment]
Latest commit: https://github.com/MDXDave/mdl-selectfield

**Comment by alorma** [comment]
Could you please check with latest release? V.2.10.7? It doesn't happens to me

**Comment by MDXDave** [comment]
It's fixed in newest Version.
