### ISSUE TITLE
Pull request commits refresh bug

### ISSUE THREAD

**Issue by alashow** [gitskarios/Gitskarios#403]
_Issue:_ 
Pull request commits refresh bug. When refreshing, refreshlayout progress view stucks and list duplicate entries.

> App version - 2.9.4
> 
> Git build hash from settings: 83a7338
> 
> Device - Nexus 5x
> 
> Device android version - Android 6.0.1

_Steps to reproduce:_
Open any pull request, open commits tab, refresh (pull down)

_Crash (optional):_

_Screenshots_
https://drive.google.com/open?id=0B5up2CgQawSDSFZPVDlkUVpkRXc

**Comment by farbodsz** [comment]
A similar situation occurs when you refresh the 'Events' list - the list items get duplicated. 

I think this is important enough to get reopened.
