### ISSUE TITLE
Assets are misaligned on Android N

### ISSUE THREAD

**Issue by splendidbits** [gitskarios/Gitskarios#407]
May only be an Android N issue, but we're approaching preview 3, so I thought I'd bring it up. Note the following screenshots. 

![](https://drive.google.com/a/staticfish.com/uc?export=view&id=0B1IKahZmzO9CdndZaVVIU0ptRVU) 

![](https://drive.google.com/a/staticfish.com/uc?export=view&id=0B1IKahZmzO9CU2JVNVQwRno0bjA)

**Comment by alorma** [comment]
I know, it's a N error, in iconics library.

@mikepenz knows it

**Comment by splendidbits** [comment]
Thanks @alorma. Feel free to close or reassign. :-)

Great app btw.

**Comment by mikepenz** [comment]
@splendidbits yeah I know about this issue, but I will not investigate right now because it was introduced in Preview 2 and was not existing in Preview 1. So I expect it to be resolved in Preview 3. If not I will start investigating by then
