### ISSUE TITLE
Following tabs incorrect empty messages 

### ISSUE THREAD

**Issue by lgoudriaan** [gitskarios/Gitskarios#413]
The empty messages on the following and followers tabs are incorrect.

**Comment by alorma** [comment]
Thanks, will fix tomorrow

**Comment by alorma** [comment]
Following:

`There isn't anyone following you`

Followers:

`There aren't any followers`

What's the problem?

**Comment by lgoudriaan** [comment]
Following are the people who you are following.
Followers are the people who are following you.

**Comment by alorma** [comment]
Ah ok i see, sorry.

I will fix later

**Comment by lgoudriaan** [comment]
No problem.
Didn't had any time to get behind a computer and fix them by myself.
