### ISSUE TITLE
Unable to Comment on a Pull Request, Button is untouchable

### ISSUE THREAD

**Issue by shyim** [gitskarios/Gitskarios#417]
_Issue:_
Unable to Comment on a Pull Request, Button is untouchable

> App version
> 2.13.0
> Git build hash from settings:
> b5b55a8
> Device
> Google Nexus 7 (2013)
> Device android version
>   6.0.1 Stock Android

_Steps to reproduce:_
Go to any Repository and click on a Pull Request which has comments

_Screenshots_
![screenshot_20160521-133329](https://cloud.githubusercontent.com/assets/6224096/15448145/76eaa868-1f59-11e6-8607-d5b492a6f714.png)

**Comment by alorma** [comment]
Uhmmmm ok thanks.

That's because it's a Tablet, right? I will fix it as soon as i can

**Comment by shyim** [comment]
Yes it's a Tablet. Thanks for so fast response lol :)

**Comment by alorma** [comment]
That's why i enabled push into Gitskarios ;)

**Comment by chenzhuwei** [comment]
这是什么啊！

------------------ 原始邮件 ------------------
发件人: "Shyim"; 
发送时间: 2016年5月21日(星期六) 晚上7:42
收件人: "gitskarios/Gitskarios"; 
主题: Re: [gitskarios/Gitskarios] Unable to Comment on a Pull Request,Button is untouchable (#417)

Yes it's a Tablet. Thanks for so fast response lol :)
