### ISSUE TITLE
Infinite loading Stared Repositories

### ISSUE THREAD

**Issue by shyim** [gitskarios/Gitskarios#418]
_Issue:_
i tryed also with adb to get a usefull message why its only loading and it shows nothing.

> App version
> 2.13.0
> Git build hash from settings:
> b5b55a8
> Device
> Google Nexus 7 (2013) or Meizu MX4 Pro
> Device android version
>  6.0.1 Stock Android

_Steps to reproduce:_
Go to Repositories Overview and switch to Tab Stared

_Screenshots_

![screenshot_20160521-214024](https://cloud.githubusercontent.com/assets/6224096/15450493/2959574a-1f9d-11e6-92dc-384299284d86.png)

**Comment by alorma** [comment]
Oh. Sorry for that!!!

I will send you a Debug APK so you can see the logs.

It doesn't happen my device

**Comment by shyim** [comment]
@alorma i tryed your last commit with a forked app its works. Thanks <3

**Comment by alorma** [comment]
Thanks! Glad to hear that!
