### ISSUE TITLE
No Action on Branch Switch Icon on Repository View

### ISSUE THREAD

**Issue by shyim** [gitskarios/Gitskarios#420]
_Issue:_
No Action on Branch Switch Icon on RepositoryActivity

> App version
> 2.13.0
> Git build hash from settings:
> c37843b
> Device
> Google Nexus 7
> Device android version
>  Android 6.0.1

_Steps to reproduce:_
1. Go to any Repository which has branches
2. Touch on Branch Switch Icon at the Top

_Screenshots_

![device-2016-05-22-105728](https://cloud.githubusercontent.com/assets/6224096/15453187/27680408-200c-11e6-92fd-709b95759422.png)

**Comment by alorma** [comment]
Done!
