### ISSUE TITLE
Android Notifications are missing after Update

### ISSUE THREAD

**Issue by shyim** [gitskarios/Gitskarios#422]
_Issue:_
On the new Version the Android Notifications are missing

> App version
> 
> Git build hash from settings:
> bb5ea8f
> Device
> Google Nexus 7
> Device android version
>  Android 6.0

_Steps to reproduce:_
Open NavigationDrawer

_Screenshots_
Current:
![screenshot_20160522-211657](https://cloud.githubusercontent.com/assets/6224096/15455959/b903b8d4-2062-11e6-846c-38b2f15f0d4c.png)

Store Image:

![](https://lh3.googleusercontent.com/0gujoP1O-IC4KaIzv3s0mRCe4EU20I5MdLN_AXstLigcnlVWfTY60XYeyqFSyxAidE4=h900-rw)

**Comment by alorma** [comment]
No.

Notifications are not missing, it still work, what i deleted is the switch, i'm going to add into the notifications screen by itself.

Sorry, i will add today or tomorrow

**Comment by shyim** [comment]
Ohhh No Problem! :)

**Comment by alorma** [comment]
Fixed on 2.17 :)
