### ISSUE TITLE
Boton reportar bug

### ISSUE THREAD

**Issue by aballano** [gitskarios/Gitskarios#427]
El boton de reportar bug tiene dos fallos:

-En inglés dice "Found bug?" lo cual es incorrecto, yo sugiero "Bug found?" o mejor "Report bug"

-El segundo problema es que no está alineado con los otros botones, por lo que queda algo raro ya que parece un submenú (visto en un nexus 5x)

Pd: también estaría genial poder enviar una captura de pantalla en el reporte :)

Saludos!

**Comment by alorma** [comment]
Lo del "Found bug" me parece buena idea!

La alineacion, està hecho express! Pero vaya, no se entiende, no?

**Comment by alorma** [comment]
Para la subida de fotos... firebase al rescate! Dejame pensar en eso un poco :)

**Comment by alorma** [comment]
Cierro este issue.

Estoy trabajando en lo de subir imagenes
