### ISSUE TITLE
Graphical glitches while scrolling

### ISSUE THREAD

**Issue by tajnymag** [gitskarios/Gitskarios#428]
Code blocks are rendered over system window. I'm running CM13 on Oneplus One. Doesn't happen in any other app. 

![](http://i.imgur.com/UOBw6rm.jpg)

**Comment by GeorgeWL** [comment]
Can confirm, only happens on commits with lots of changes to files, it's like it's a problem with overflow.

**Comment by alorma** [comment]
Please, link of commit, i will check

**Comment by GeorgeWL** [comment]
![](http://imgur.com/Cx40bth)

Sony Xperia z5 Standard with Android stock Lollipop

**Comment by GeorgeWL** [comment]
Marshmallow even 

![](http://i.imgur.com/Cx40bth.png)

**Comment by Tajnymag** [comment]
@alorma For example here: https://github.com/PCSX2/pcsx2/pull/1370

**Comment by GeorgeWL** [comment]
@alorma it seems that it doesn't happen in every case, even on the same commit so I can't show it on a specific repository really.

**Comment by nyancrimew** [comment]
Just wanted to report that too... For me it seems to always occur with every commit with more files than my phone is able to display at once.

OnePlus 2 with Marshmallow

**Comment by alorma** [comment]
Hope this is fixed now guys!
