### ISSUE TITLE
New themes colors issues

### ISSUE THREAD

**Issue by shyim** [gitskarios/Gitskarios#434]

**Comment by alorma** [comment]
Fixed (beta)! Thanks

**Comment by shyim** [comment]
Same is on Commit View

**Comment by alorma** [comment]
Thanks!

**Comment by alorma** [comment]
Same in PR screen

**Comment by alorma** [comment]
Hi @shyim i just uploaded a new version to beta, could you test it?

**Comment by shyim** [comment]
Thanks. I will try it when  it is available. Play store is so slow

**Comment by shyim** [comment]
Looks fine

**Comment by alorma** [comment]
https://github.com/gitskarios/Gitskarios/issues/442

**Comment by chenzhuwei** [comment]
这个什么

陈助威

上海软慧信息技术有限公司

18516527207

上海市闵行区虹桥镇合川路2679号（虹桥国际商务广场B座5F）

------------------ 原始邮件 ------------------
发件人: "Bernat Borrás Paronella"; 
发送时间: 2016年6月4日(星期六) 凌晨5:29
收件人: "gitskarios/Gitskarios"; 
主题: Re: [gitskarios/Gitskarios] New themes colors issues (#434)

#442

**Comment by shyim** [comment]
I found a new color issues on RepoView:
Gif: http://i.imgur.com/1frpckk.gifv

**Comment by alorma** [comment]
Done with that one :P

**Comment by alorma** [comment]
Hi @shyim

I'm thinking about **Assigned issues** page, should it be green? Issues are something inside of repository, but not sure about it
