### ISSUE TITLE
No repositories found sign is flashing

### ISSUE THREAD

**Issue by pkramme** [gitskarios/Gitskarios#436]
_Issue:_After opening the repositories tab, the sign "No repositories found" is flashing multiple times at the bottom, even if there are repositories.

> App version
> 2.13.2
> Git build hash from settings:
> 7f637ab
> Device
> Samsung Galaxy S5
> Device android version
> Android 5.0

_Steps to reproduce:_
Open the repository tab

_Screenshots_
![screenshot_bug_no_repository_found](https://cloud.githubusercontent.com/assets/19418956/15713921/b59b6cc4-2818-11e6-8dec-f5417e74110b.png)

**Comment by alorma** [comment]
Hi.

I guess it's happening because you don't have repos in any of the other tabs... could you check it plz?

**Comment by pkramme** [comment]
I don't have any in "Contributed" and "From Organizations". By the way, shouldn't there be something in Contributions when i make an issue like this, or is this only for pull requests?

**Comment by alorma** [comment]
Should be fixed, if not, please reopen

**Comment by pkramme** [comment]
Thank you!
