### ISSUE TITLE
Upload image and insert link,  Github style 

### ISSUE THREAD

**Issue by GeorgeWL** [gitskarios/Gitskarios#439]
I feel that, as a feature, the ability to upload directly into a comment and have the app convert to a Github upload and then have it link it automatically would be a great feature.

**Comment by alorma** [comment]
https://github.com/gitskarios/Gitskarios/pull/437

:)

**Comment by GeorgeWL** [comment]
Pity that the github as API doesn't really have any support for image upload, cause I'd rather imgur didn't get even more money from the adverts.

**Comment by alorma** [comment]
Close, work and comment on https://github.com/gitskarios/Gitskarios/issues/432
