### ISSUE TITLE
Incorrect "no repositories found" snackbar

### ISSUE THREAD

**Issue by Koitharu** [gitskarios/Gitskarios#448]
The snackbar "no repositories found" shows always, even when I have repos in list

**Comment by pkramme** [comment]
Already fixed, but not shipped. #436

**Comment by Koitharu** [comment]
Ok. thanks

**Comment by shyim** [comment]
You can also join the Beta and you will receive Updates faster :)
https://plus.google.com/u/0/communities/100177663530836613291

**Comment by pkramme** [comment]
@shyim Can't you just download the latest versions directly from GitHub? Like here: [v4.8.3](https://github.com/gitskarios/Gitskarios/releases/tag/v.2.8.3)
