### ISSUE TITLE
After Accepting Pullrequest no action

### ISSUE THREAD

**Issue by shyim** [gitskarios/Gitskarios#451]
_Issue:_
After Pressing on Button "Merge" the app shows no interaction. I must go back to the Repository and again in the Pull Request to show the result :)

> App version
> 2.14.9
> Git build hash from settings:
> 09d900c
> Device
> Nexus 7
> Device android version
>  Android 6.0.1

_Steps to reproduce:_
Go to any Pull Request and Press "Merge"

**Comment by alorma** [comment]
Thks!
