### ISSUE TITLE
Cannot log in with passwords having special characters 

### ISSUE THREAD

**Issue by jgkamat** [gitskarios/Gitskarios#457]
My password on gh has a bunch of special characters, and I get a "error login"  message when trying to login to the app. My password has some of these characters: `':%$&() =+/-_!? *",. #;@` as well as the backtick:` itself 

Let me know if you cannot reproduce

**Comment by alorma** [comment]
Hi.

I will check later :)

**Comment by jgkamat** [comment]
I did a little bit of testing and I think that percent:% seems to be one offending character 
It could be more, but any password with a % definitely fails 

I _think_ this is failing on the one just pushed to Google play

**Comment by alorma** [comment]
Mmmm

I just checked with a test account the password `aaaa%aaaa1` and it seems to work.

Could you provide a failing password?

**Comment by jgkamat** [comment]
~~`Aaaaaaa"3aa` seems to fail for me.~~

I made a mistake before, I hadn't restarted the app when I updated it. The % char seems to work now.

You can also reproduce this w/o changing your password, as the request itself dosent send 

EDIT: actually somethings wrong on my end, give me a few minutes.

**Comment by jgkamat** [comment]
Ok, I think this password is failing for me too:
`jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj`

I think that's 60 js? My password is very long :/

I wasn't able to figure out the maximum length, but im pretty sure my password is hitting this too

Thanks for looking into this! =D

**Comment by jgkamat** [comment]
Can you reproduce this, or should I double check my version?

**Comment by alorma** [comment]
I cannot reproduce it :S I will check later again

**Comment by jgkamat** [comment]
I just shortened my password to about 40 characters and that fixed it. This can be closed if you still can't reproduce this

**Comment by enj** [comment]
I am having this same issue - I also have a super long password with all character types.

**Comment by lgoudriaan** [comment]
Wasn't able to login with my old password after reinstall. 

My old password was: 
Eiiwt0bgi4bEkwcmKIftgp133EhdZgA1Y7rJm7Ht2ZBm4u401S

**Comment by alorma** [comment]
Will try with that, thanks
