### ISSUE TITLE
Inconsistent theming when using dark theme

### ISSUE THREAD

**Issue by matthieugrieger** [gitskarios/Gitskarios#458]
Hi there,

First of all, great app! Probably the best GitHub Android client I've used so far.

I've come across some issues with UI styling when using the dark theme. Below is a link that shows some screenshots of what I'm talking about:

https://imgur.com/a/wQKaG

I'm not sure if the coloring on the README is intentional, but in any case it is a bit straining on the eyes when viewing it at night, which is why I use the dark theme in the first place.

In the second screenshot you can see that the usernames are hardly readable due to the white text on a gray background.

Hopefully this helps, thanks!

**Comment by alorma** [comment]
Hi.

Thanks for that screenshots!

I will check later, and publish a new release

**Comment by matthieugrieger** [comment]
Thanks for the update, the issue view looks great now. :) Just two other minor things that I've noticed:

The text on READMEs is now a bit hard to read as the font color is black on a gray background: http://i.imgur.com/DXdAwBN.png 

Also, when submitting issues the bar at the bottom is still white: 
http://i.imgur.com/p4ZS663.png

I hope I'm not coming across as overly nitpicky; just want to help out as much as possible. :)

**Comment by alorma** [comment]
It should be white o_o

I will update the markdown renderer today, hope it fixes

**Comment by alorma** [comment]
Color of readme fixed

Only the issue editor remains white

**Comment by alorma** [comment]
Reactions still white

**Comment by matthieugrieger** [comment]
Just updated, markdown rendering is fixed. :)

**Comment by alorma** [comment]
Milestones activity:

![Screenshot_20160623-225653.png](http://i.imgur.com/Km9HOIW.png)

**Comment by GeorgeWL** [comment]
I'd suggest for the bit below editor to rather go for a slate grey, so that it's obviously a separate element but not such a stark contrast.
