### ISSUE TITLE
Caching organization repo

### ISSUE THREAD

**Issue by JonatanSalas** [gitskarios/Gitskarios#459]
If you search for a particular organization you can see correctly the repos that it has. But if you search or look into a new organization, you will find that it retrieves the repos of the first you have entered. 

This sometimes happens when you look into a normal github user! 

Hope you can solve this! This app is amazing

**Comment by alorma** [comment]
what's your app version?

**Comment by JonatanSalas** [comment]
After updating the application this stop, so maybe I was using a non-updated versión!

**Comment by alorma** [comment]
Reopen just for test purpose
