### ISSUE TITLE
Leaving source code view resets repository activity

### ISSUE THREAD

**Issue by davidschreiber** [gitskarios/Gitskarios#463]
When navigating through the sources of a repository, and then clicking a Java file a source code viewer is opened. When leaving the source code viewer either by pressing back, or by pressing the back button in the action bar the current repository repo is reset to the first tab (repo overview). When navigating to the file tree tab it is again at the repository root (while previously it was navigated to a subfolder containging the viewed file). This is very annoying, since viewing a file and then another file is a very tedious process.

**Comment by alorma** [comment]
Done
