### ISSUE TITLE
Source code is not displayed correctly 

### ISSUE THREAD

**Issue by jonathanmaron** [gitskarios/Gitskarios#466]
When I click on a file (a PHP file) the source code viewer is opened, and the file is displayed. However the file is heavily truncated. Only about 6 lines are displayed. Furthermore the background is dark yet I have the light theme enabled. This problem did you not exist in the previous version of the app.

**Comment by jonathanmaron** [comment]
Screenshot of the issue:
https://s3.amazonaws.com/o3cxerf5/Public/jwpsh5kh/20160617060354.png

The screenshot shows the display of this file: 
https://github.com/TextControl/txtextcontrol-reportingcloud-php/blob/master/src/Filter/DateTimeToTimestamp.php

**Comment by alorma** [comment]
Ok.

It seems is a problem with the `<?php`, i've opened an issue in the highlight library that i use:

https://github.com/PDDStudio/highlightjs-android/issues/2

**Comment by jonathanmaron** [comment]
It looks like the author of the library has fixed this problem now. Could you please update your app to use the latest library? Thank you most kindly.

**Comment by alorma** [comment]
I've updated it, but php files aren't loaded correctly yet

**Comment by shyim** [comment]
It looks so Gitskarios is 1.1.0 using (https://github.com/gitskarios/Gitskarios/blob/develop/app/build.gradle#L195) , but 1.2.0 is available https://github.com/PDDStudio/highlightjs-android/releases/tag/1.2.0

**Comment by alorma** [comment]
Fixed :)

**Comment by shyim** [comment]
Works for me fine :)

**Comment by jonathanmaron** [comment]
When do you expect to release the fixed version to the Google Play store?

**Comment by alorma** [comment]
This weekend. I have to fix a few things yet

**Comment by jonathanmaron** [comment]
Awesome. Thank you very much for attending to this issue. I very much appreciate it!

**Comment by jonathanmaron** [comment]
I just installed the latest version from the Google Play store and can confirm that the issue is fixed. Thank you.
