### ISSUE TITLE
loss of line breaks when tab out

### ISSUE THREAD

**Issue by GeorgeWL** [gitskarios/Gitskarios#473]
**_2 Upvotes**_ Android M
Gitskarios 2.15.3
Sony Xperia Z5 (standard)

For example, I can put in formatting for this line break. 

Then when tab out, they're gone.
 And have to reformat again.

 Doesn't seem to effect any other markup however, like code blocks, links etc, only line breaks. 

[gfycat gif](https://gfycat.com/QuarterlySpotlessAfricanclawedfrog)

**Comment by GeorgeWL** [comment]
:+1:

**Comment by alorma** [comment]
👍  will check

**Comment by GeorgeWL** [comment]
Closed because figured it out or not repeatable?

**Comment by alorma** [comment]
C/osed because fixed
