### ISSUE TITLE
Codeview missbehaving

### ISSUE THREAD

**Issue by pkramme** [gitskarios/Gitskarios#476]
![Screenshot_2016-07-03-10-49-11.png](http://i.imgur.com/si84xUU.png) 
![Screenshot_2016-07-03-10-49-03.png](http://i.imgur.com/0nOD9oP.png)
The '#include' part is somehow missing.

**Comment by alorma** [comment]
Link to file?

**Comment by pkramme** [comment]
https://gist.github.com/paulkramme/5b482deaea7f1ca0e1b29050b1a40f3a

On Sun, Jul 3, 2016, 12:01 Bernat Borrás Paronella notifications@github.com
wrote:

> Link to file?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/gitskarios/Gitskarios/issues/476#issuecomment-230160528,
> or mute the thread
> https://github.com/notifications/unsubscribe/AShPTCQS4YqQhKrnQH1eWSDghNww4SV5ks5qR9zFgaJpZM4JD4ge
> .
> 
> ## 

Paul Kramme

**Comment by alorma** [comment]
Thanks

**Comment by pkramme** [comment]
![Screenshot_2016-07-03-22-13-57.png](http://i.imgur.com/tsxeAEM.png)
Same applies for same content in repository. I'm gonna rename issue.

**Comment by pkramme** [comment]
All .xml files i tried wont work. Test file: https://github.com/Minitour/crofis-android-uikit/blob/master/ui/src/main/res/drawable/background_fill.xml 
![Screenshot_2016-07-03-22-18-20.png](http://i.imgur.com/liukwLc.png)

**Comment by pkramme** [comment]
I will close this as this is a duplicate of #466
