### ISSUE TITLE
states that comment failed then posts comment anyway.

### ISSUE THREAD

**Issue by GeorgeWL** [gitskarios/Gitskarios#477]
**_1 Upvote**_ Example https://gfycat.com/CaringYawningHoneybadger

This happens every time consistently.

**Comment by GeorgeWL** [comment]
:+1:

**Comment by alorma** [comment]
Test

Test

**Comment by alorma** [comment]
Fixed!

**Comment by GeorgeWL** [comment]
What was the cause in the end?

**Comment by alorma** [comment]
A string error :P
