### ISSUE TITLE
Problems with Eventmanaging

### ISSUE THREAD

**Issue by pkramme** [gitskarios/Gitskarios#481]
I can't really explain...
![Screenshot_2016-07-05-14-56-36.png](http://i.imgur.com/QgXNda2.png)

**Comment by alorma** [comment]
I can u_u

What events are? I will try to fix

**Comment by alorma** [comment]
![Screenshot_20160705-212313.png](http://i.imgur.com/eay2juT.png)

That's caused because there are some events that aren not handled.

I will fix later

**Comment by pkramme** [comment]
I think these are wiki edits... I will check when i'm back at my laptop.

**Comment by shyim** [comment]
I had it often too, most cases it was a comment on a commit line
