### ISSUE TITLE
MIT License improvement

### ISSUE THREAD

**Issue by pkramme** [gitskarios/Gitskarios#483]
As i just found out: The MIT License, to be more specific, this part

`The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.`

states that you have to include the MIT License within every part, that means every file, to be fully covered.
Hope this can help.

**Comment by GeorgeWL** [comment]
I think that the "substantial portions" means it can be fine with just a short mention in each sizeable module that's used.

**Comment by pkramme** [comment]
IMO it's every part that contribute to the project, so every file. But if
you don't think its necessary i'll close it.

**Comment by pkramme** [comment]
Which leads to the creation of a new issue: I can't close it :D

**Comment by GeorgeWL** [comment]
not an issue @paulkramme , GitHub allows organisations/repositories to
decide on roles and one of the options (which gitskarios uses for theirs)
is to only allow approved users to close issues.

**Comment by pkramme** [comment]
Yes but it's my issue, isnt it?

**Comment by pkramme** [comment]
If this has still relevance, i've [developed a little script](https://github.com/paulkramme/mit-license-adder) which could do this job.

**Comment by GeorgeWL** [comment]
I still think that it's only necessary on each unique module that we pulled in from elsewhere and one at the root for ours.
