### ISSUE TITLE
unable to load issue threads with lots of comments. 

### ISSUE THREAD

**Issue by GeorgeWL** [gitskarios/Gitskarios#484]
I noticed this on the "edit from within app" issue, that since the comment chain increased past a certain length it doesn't seem to load when I open, just a loading animation. 

I'm not sure if it will eventually load, but left it going for about a minute and a half with no load.

**Comment by pkramme** [comment]
Happens for me too. I tried for about 10 Minutes for testing this.

**Comment by alorma** [comment]
Yes. Reproduced

**Comment by pkramme** [comment]
The app can't load an issue after 30 comments. The app is misbehaving and has to be force closed after some time. At new startup the app crashes again and gives the folowing error:

**Comment by pkramme** [comment]
Build version: 2.16.9 
Build date: 2016-07-14 20:14:42 
Current date: 2016-07-14 23:25:42 
Device: Samsung SM-G900F 

Stack trace:  
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack available

**Comment by alorma** [comment]
Fixed :)

Thanks guys for reporting it, and help me testing
