### ISSUE TITLE
Add closing function for own issues

### ISSUE THREAD

**Issue by pkramme** [gitskarios/Gitskarios#485]
I can't close my own issues.

**Comment by pkramme** [comment]
I can't close my own issues.

**Comment by GeorgeWL** [comment]
this is a part of github, not gitskarios, it's not possible on the desktop version either.

Approved submitters can close them however.

**Comment by pkramme** [comment]
Nope, this was the webversion

**Comment by GeorgeWL** [comment]
oh, seems I'm wrong, huh, didn't even know you could do that.

**Comment by alorma** [comment]
Yes, users who opened an issue can close it afaik

I will check
