### ISSUE TITLE
add functionality option to open images in modal style within app

### ISSUE THREAD

**Issue by GeorgeWL** [gitskarios/Gitskarios#487]
Just think it's a nice addition, in the same style as this for example 
![Screenshot_20160707-152049.png](http://i.imgur.com/QXGejC3.png)

**Comment by pkramme** [comment]
I don't like the idea... The pictures are already shown, so what's the point?

**Comment by GeorgeWL** [comment]
Quite simple,  the pictures are already shown but only in thumbnail.  Which isn't particularly useful for images with lots of detail, and in my opinion it detracts from the experience when you have to open a thumbnail in browser. 

And I did suggest that if should be made as an optional part of the ui, as I'm well aware that not everyone likes that method, but quite a lot do.

**Comment by GeorgeWL** [comment]
And by optional I just mean turn it on or off with a checkbox.

**Comment by alorma** [comment]
I like the idea, i will think about it.

Btw guys, do you want to join gitskarios as contributors?

**Comment by pkramme** [comment]
Sure!

**Comment by pkramme** [comment]
You have a point @Georgiel.

**Comment by alorma** [comment]
Added @paulkramme! Now you can write in gitskarios itself

**Comment by pkramme** [comment]
Thank you!

**Comment by GeorgeWL** [comment]
hmm, alright. tbh, not sure what I'd do, I have basically no experience in writing for mobile apps, still an undergrad.

**Comment by pkramme** [comment]
Doesn't matter... I do not have Android experience to, but i'm trying to
learn. And this is the best place to do. Just trust yourself and try to fix
basic issues. And after that you could go further.

**Comment by alorma** [comment]
I've added ability to make zoom on imageview, won't update more for now

**Comment by GeorgeWL** [comment]
Where's the option for that @alorma??

**Comment by alorma** [comment]
Just open the image, and you can make zoom
