### ISSUE TITLE
Slack for gitskarios

### ISSUE THREAD

**Issue by alorma** [gitskarios/Gitskarios#489]
Hey!<br /><br />If you want to discuss something about gitskarios, i have a Slack!<br /><br />http://gh-apps.slack.com<br /><br />@paulkremmer<br />@georgiel

Add a comment if you want to join

**Comment by pkramme** [comment]
Yes, i'd like to join, more collaboration is better, isn't it, but doesn't it cost something?

**Comment by alorma** [comment]
No, slack is free with some limitations :b

**Comment by pkramme** [comment]
Well then, i'd like to have slack access then :+1:

**Comment by alorma** [comment]
I've seen you a mail from gh-apps :)

**Comment by GeorgeWL** [comment]
Yeah sure why not.

**Comment by alorma** [comment]
@georgiel i need your mail to invite you. Or write me at gitskarios@gmail.com

**Comment by pkramme** [comment]
I recommend setting up an email account for work only, like GitHub, slack, etc...

**Comment by Georgiel** [comment]
georgelangham1990@gmail.com

**Comment by GeorgeWL** [comment]
Is there a way to change the name of the Slack? Gh-Apps has no context so it could be confused with another channel.

**Comment by alorma** [comment]
Done

`gitskarios.slack.com`
