### ISSUE TITLE
Nightly Builds?

### ISSUE THREAD

**Issue by pkramme** [gitskarios/Gitskarios#492]
Nightly Build and/or Beta builds could improve stable code quality, because bugs can be found faster and anyone who wants have quicker access to new functions.

**Comment by alorma** [comment]
Yes.

I have to re-enable fabric distribution

**Comment by alorma** [comment]
I've added you to fabric alpha releases

**Comment by pkramme** [comment]
Thank you, but wouldn't be easier to make releases on GitHub?

**Comment by alorma** [comment]
mmm nop

because tag releases are sent to automatically to play store, in production branch, so i won't publish everything :P
