### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by shyim** [gitskarios/Gitskarios#494]
It look so that Star icon and other are missing in the new app version

![Screenshot_20160709-013408.png](http://i.imgur.com/e7VYzCp.png)

**Comment by shyim** [comment]
Lol assign field was empty..

**Comment by alorma** [comment]
@mikepenz do you know what happened?

**Comment by mikepenz** [comment]
I might have am idea. Will take a look as fast as possible

Bernat Borrás Paronella notifications@github.com schrieb am Sa., 9. Juli
2016, 10:57:

**Comment by mikepenz** [comment]
This is related to the following: https://github.com/mikepenz/Android-Iconics/issues/182
Caused by changes required to fix the following: https://code.google.com/p/android/issues/detail?id=210834&thanks=210834&ts=1463954825

**Comment by alorma** [comment]
Ok @mikepenz

So is there anything i can do? Or should i move to regular drawables?

**Comment by mikepenz** [comment]
@alorma I am currently fixing it. there will be a PR soon
