### ISSUE TITLE
Weird toolbar behaviour when writing an issue description

### ISSUE THREAD

**Issue by farbodsz** [gitskarios/Gitskarios#497]
When creating an issue and writing a description for it, if the description is long so that it needs to scroll, the toolbar scrolls with it as well.

![Screenshot_2016-07-11-15-26-13.png](http://i.imgur.com/5FYytqZ.png)

Perhaps this is intentional, but it seems strange as I would expect the content to scroll and the toolbar to stay fixed.

**Comment by alorma** [comment]
This only happens with keyboard open?

**Comment by farbodsz** [comment]
Yes. 

You can see here:

![Screenshot_2016-07-11-15-38-59.png](http://i.imgur.com/B1BZJTg.png)

**Comment by alorma** [comment]
Ok

So, i thinks it's the desired behaviour. Android does it automatically for edit texts.

If this is upvoted, i will try to change it

**Comment by farbodsz** [comment]
Fair enough - thanks.
