### ISSUE TITLE
Milestone page doesn't display any issues

### ISSUE THREAD

**Issue by farbodsz** [gitskarios/Gitskarios#501]
When issues have been added to a milestone, and I view that milestone on Gitskarios, none of the issues get displayed.

**Comment by alorma** [comment]
Sorry to hear that

I will check asap, could you provide a repository link?

**Comment by farbodsz** [comment]
It's a private repository.

But maybe that's why it's not displaying correctly.

**Comment by alorma** [comment]
OK, i will check, thanks

**Comment by alorma** [comment]
I've tested in my private repositories, and it works as expected :s

I don't know what's happening.

I will add an empty and error states no that screen, can't do more if i don't have access to the repo :s

**Comment by farbodsz** [comment]
@alorma  Okay, I have given you access to the repository as a collaborator so we can find a solution to the issue.

**Comment by alorma** [comment]
Thanks!

**Comment by alorma** [comment]
Ok, reproduced! I will check how to fix it

**Comment by farbodsz** [comment]
That was quick!

Thank you.

**Comment by alorma** [comment]
Fixed! Uploading a new version :D

**Comment by farbodsz** [comment]
Thank you!
