### ISSUE TITLE
titles of files in file view are centered

### ISSUE THREAD

**Issue by frederickk** [gitskarios/Gitskarios#504]
![Screenshot_20160715-133741.png](http://i.imgur.com/iAH5SyP.png)

**Comment by alorma** [comment]
Hi

That doesn't looks fine :(

Which version of android are you using?

**Comment by pkramme** [comment]
Happens to me too. Android 5.0

**Comment by lgoudriaan** [comment]
I have the same problem. Android 6.0.1

I was trying to fix this but wasn't able to build the project due an error on resValue "string", "imgur_client_id", getImgurClient() in gradle, value null :s

**Comment by alorma** [comment]
Hey, yes.

Just replace the method with any string

**Comment by frederickk** [comment]
I'm on Android 6.0.1 as well.

**Comment by alorma** [comment]
@frederickk is it fixed?

**Comment by lgoudriaan** [comment]
Yep, it's fixed
