### ISSUE TITLE
How to join beta

### ISSUE THREAD

**Issue by ntimo** [gitskarios/Gitskarios#506]
Hello,

I tried the link in the description from the play store but when clicking the link it says Iam not allowed to join. So how can I get the beta version? Of this amazing app?

**Comment by alorma** [comment]
You should join the g+ community.

But i do not post much in beta anyway

**Comment by ntimo** [comment]
Could you provide me with a link to the Community?

**Comment by alorma** [comment]
https://plus.google.com/communities/100177663530836613291

**Comment by GeorgeWL** [comment]
I'd suggest to remove the other beta link from the play store description,  it confuses matters.

**Comment by alorma** [comment]
@Georgiel feel free to modify it :)
