### ISSUE TITLE
Add Account button opens 404 Page

### ISSUE THREAD

**Issue by pkramme** [gitskarios/Gitskarios#518]
![Screenshot_2016-07-27-09-31-43.png](http://i.imgur.com/qJ0eHAw.png)
This page opens when i'm clicking the add account button.
https://github.com/login/oauth/authorize?client_id=null&scope=gist,user,notifications,repo

**Comment by alorma** [comment]
Hi.

Which version are you using?

**Comment by pkramme** [comment]
Latest Dev version

**Comment by alorma** [comment]
Ok.

Where is the button you click? I'm not using oauth since long time ago

**Comment by pkramme** [comment]
![Screenshot_2016-07-27-09-46-46.png](http://i.imgur.com/PA6ZGo6.png)

**Comment by alorma** [comment]
Lol!

This is a really OLD one version.

You should update from the latest dev version.

ok, you tried the beta from fabric, isn't It was just a test, not a real latest update

**Comment by GeorgeWL** [comment]
I'd suggest either keeping the fabric betas up to date, or turning the fabric beta option off completely, should help prevent this confusion.

**Comment by alorma** [comment]
Yes.

I've updated it by error.

But i will keep it updated, don't worry :)
