### ISSUE TITLE
Can't update website files!

### ISSUE THREAD

**Issue by mariobrostech** [gitskarios/Gitskarios#524]
A few days ago, I was able to update files and push new commits. Now, for some strange reason, I get errors while trying to push commits to my website pages! It says that an unknown error occurred.

**Comment by alorma** [comment]
What you mean by website pages?

**Comment by mariobrostech** [comment]
Like editing a document in the website (example: index.html)

**Comment by GeorgeWL** [comment]
can you give us in as much detail when exactly it happens and how?

See, if we can then repeat the same steps whilst running it on a virtual machine, we should be able to see what caused it.

**Comment by mariobrostech** [comment]
Nevermind , I think it was fixed in the last commit that I made.

**Comment by mariobrostech** [comment]
*Nevermind (stupid autocorrect)

**Comment by GeorgeWL** [comment]
@mariobrostech safe to close then? We've not checked it yet you see.

**Comment by mariobrostech** [comment]
Safe to close!
