### ISSUE TITLE
multiple assignees

### ISSUE THREAD

**Issue by alorma** [gitskarios/Gitskarios#525]
Add multiple assigness, it's now official on API<br /><br />(test issue: https://github.com/gitskarios/Gitskarios/issues/521)

**Comment by GeorgeWL** [comment]
Ah, I'll probably have to wait for my version to notice,  it seems play store needs about half an hour to propagate the changes to UK.

**Comment by alorma** [comment]
?

I not implemented it yet, just add as issus to develop it someday

**Comment by GeorgeWL** [comment]
Ooh right,  thought made this issue to show it off like a "lookit the example!"
