### ISSUE TITLE
Username is displayed with unrelated numbers

### ISSUE THREAD

**Issue by geekrainy** [gitskarios/Gitskarios#527]
RT

![IMG_20160803_192244.png](http://i.imgur.com/ZXfrj5l.png)

![IMG_20160803_192230.png](http://i.imgur.com/83rodj3.png)

![IMG_20160803_192138.png](http://i.imgur.com/Si12H8e.png)

**Comment by pkramme** [comment]
Please rewrite this issue in English. We cannot understand you. Please look at the [Contribution Guide](https://github.com/gitskarios/Gitskarios/blob/develop/CONTRIBUTING.md) for more information.

**Comment by pkramme** [comment]
I think i got it now: They are numbers behind the name, which doesn't belong to the actual user name.

**Comment by alorma** [comment]
Yes. I know the problem.

I will fix as soon as possible

PS: related to multiple accounts on Android N (bug)
