### ISSUE TITLE
Hi, 

### ISSUE THREAD

**Issue by almisbmn** [gitskarios/Gitskarios#528]
Sorry this was by mistake, I've submitted two issues by accident, the other one has the description and the screenshot and GitHub doesn't allow you to remove one.
I apologize again.

**Comment by GeorgeWL** [comment]
don't waste our time @almisbmn

**Comment by GeorgeWL** [comment]
@almisbmn it's ok. At first I assumed you were a spammer, but then looked at profile and it's obvious you're not.
