### ISSUE TITLE
Play Store Payment Error

### ISSUE THREAD

**Issue by almisbmn** [gitskarios/Gitskarios#529]
Thank you for the fantastic app,
I get a Play Store error when I try to support development as you can see from the attached picture.
Thanks again,
![Screenshot_20160804-193505.png](http://i.imgur.com/qlKPcM9.png)

**Comment by alorma** [comment]
Hi

Which version are you using?

**Comment by almisbmn** [comment]
Version 2.17.10 (217010)

**Comment by alorma** [comment]
Weird...

I will investigate
