### ISSUE TITLE
Issues tab.

### ISSUE THREAD

**Issue by ghost** [gitskarios/Gitskarios#542]
The Issues tab doesn't work and it is still named "Assigned issues".

**Comment by alorma** [comment]
Hi.

Which version are you using?

**Comment by ghost** [comment]
The latest version - 3.2.0 from the Google Play Store.

**Comment by alorma** [comment]
Ok.

Title is set to Assigned issues.

But what do you mean by tab doesn't work?

**Comment by ghost** [comment]
@alorma Issues are not shown. It says "No issue found" while I know I created issues in repositories.

**Comment by alorma** [comment]
Hi. Ok...

Maybe it's a problem with repositories from organizations, api doesn't provide them :(

**Comment by ghost** [comment]
I'm not sure but Octodroid can do this so you might want to take a look there, @alorma

**Comment by alorma** [comment]
I reopen it.

But, i don't see any problem, but, maybe that's because all my orgs memberships are public. Is that your case?

**Comment by ghost** [comment]
@alorma A what?

**Comment by alorma** [comment]
The events you can't see in the app, are from organizations?

**Comment by GeorgeWL** [comment]
@Lionir he's asking if its true of all of your organisations, or only for certain ones?

And his first guess is it might only be affecting Private organisations, so to check that he's asking if any on your feed are set to private.

**Comment by ghost** [comment]
None are private. However, I make an issue in MY repo, it does show but it doesn't issues I've created in other repos. @alorma @Georgiel

**Comment by alorma** [comment]
Mmmm, i will check, but i don't know which way i should follow :s

**Comment by ghost** [comment]
@alorma Alright, I hope it works out well :)

**Comment by ghost** [comment]
Bumping...

**Comment by alorma** [comment]
I don't see anything :s

I will provide you curl requests, so i can see if api returns something and it's a app bug

**Comment by alorma** [comment]
Hi @Lionir , please, could you execute these curl commands, and tell me the response? Not all, just if it return data, or returns error, or empty, etc...

```
curl -H "Authorization: token <ACCESS_TOKEN>" https://api.github.com/user/issues?filter=assigned
curl -H "Authorization: token <ACCESS_TOKEN>" https://api.github.com/user/issues?filter=created
curl -H "Authorization: token <ACCESS_TOKEN>" https://api.github.com/user/issues?filter=mentioned
curl -H "Authorization: token <ACCESS_TOKEN>" https://api.github.com/user/issues?filter=subscribed
```

In order to get ACCESS_TOKEN, you can create a new one in your settings, please be sure to add **repo** scope

**Comment by ghost** [comment]
@alorma Uh, I don't know hot to execute these nor do I see how to get a new token and add a repo scope..

**Comment by alorma** [comment]
Nevermind, it works now
