### ISSUE TITLE
Can't donate

### ISSUE THREAD

**Issue by xxxifan** [gitskarios/Gitskarios#544]
I wanted to support your awesome work, but the prices can't be clicked😂😂. please fix

**Comment by GeorgeWL** [comment]
Can you tell us a bit of details?

like is it always happening or only under certain circumstances?

Is there a set of steps you can find which causes it to happen every time?

and of course:

Android Version:
Handset:
Gitskarios Version: 

_(found in the drawer under about, at the top under the logo)_

(p.s that avatar is adorable.)
