### ISSUE TITLE
Remove branch from the pull-request view

### ISSUE THREAD

**Issue by juherr** [gitskarios/Gitskarios#548]
From the Web interface, you are able to remove the source branch of a pull-request once it is merged. 

I think it should be possible to do the same from an app.

**Comment by alorma** [comment]
There's nothing on the API that allows gitskariors do that

Sorry :(

**Comment by juherr** [comment]
Really ? 

Because you already display the source branch and you can remove it with https://developer.github.com/v3/git/refs/#delete-a-reference

I think the harder part is to find when the button should be displayed (once pr merged, and if the user has the right to remove the branch)

**Comment by alorma** [comment]
Uooo, great. Thanks! I was searching on "branches", sorry

**Comment by juherr** [comment]
Me too, but it was too weird that the feature was not available :)

Please, reopen the issue ;)

**Comment by alorma** [comment]
Done in https://github.com/gitskarios/Gitskarios/pull/550

**Comment by juherr** [comment]
Awesome! Thanks @LetItRock
