### ISSUE TITLE
Bug with README display  

### ISSUE THREAD

**Issue by MelvynEzi** [gitskarios/Gitskarios#551]
1. Background is transparent, turning dark theme unreadable due to standard black font color.
2. Does not fit horizontally, able to horizontally scroll.

**Comment by MelvynEzi** [comment]
Great work 👍👍
Readable on dark theme now. Just that long text (like hashes) will cause it to scroll horizontally. Or block codes like on this repo will also cause it to scroll horizontally.

**Comment by alorma** [comment]
Don't know how to fix that on css :(

**Comment by MelvynEzi** [comment]
Seems like this would help
http://www.w3schools.com/cssref/css3_pr_word-wrap.asp

**Comment by alorma** [comment]
Tried, but not seems to work :(

**Comment by MelvynEzi** [comment]
aww :( it's alright! it was harder to swipe left because the top section was able to scroll previously. it's all good now. this app seem to be the only active github client in development now, so kudos to you!
