### ISSUE TITLE
"Remove branch" button is not displayed as expected

### ISSUE THREAD

**Issue by juherr** [gitskarios/Gitskarios#554]
Related request: #548
App version: 254f063

Steps:
1. Open a pull-request on a project where you are not admin
2. Wait until the pull-request is merged
3. Try to remove the merged branch

I had a quick look on the pull-request which added the feature and the issue may be located here: https://github.com/LetItRock/Gitskarios/blob/13b83141c06cd5c9c2d31fc1e2dfe1850327c922/app/src/main/java/com/alorma/github/ui/view/pullrequest/PullRequestDetailView.java#L152
I'm not sure admin rights are checked on the good repository.

As example, on https://github.com/cbeust/testng/pull/1136 I'm not able to see the button and remove my branch.

**Comment by LetItRock** [comment]
Hello @juherr ,
yes you are right here, these permissions are not checked on proper repository... they are related to base repository... I will investigate that later how can I do that right way...  
Thanks

**Comment by juherr** [comment]
:+1: 

And I didn't check, but I wonder if collaborators of a repository and/or members of an organization are able or not to remove branches. If they can, `permissions.admin` won't be the unique solution.

**Comment by LetItRock** [comment]
Regarding to this article: [Tidying up after Pull Requests](https://github.com/blog/1335-tidying-up-after-pull-requests)
It says  that: "... you can only delete branches in repositories that you have push access to."

**Comment by juherr** [comment]
So it confirms not only admin should be able to see  the button.

**Comment by LetItRock** [comment]
Yep...

**Comment by alorma** [comment]
Yes, `permissions.admin && permissions.push` (simplified to: `permissions.push` because admins have push access)

**Comment by LetItRock** [comment]
So first we need to get permissions info from repository from which head branch comes... and then check permissions.push access rights... is that correct?

**Comment by alorma** [comment]
Yes. You should request repository, it contains permissions

**Comment by LetItRock** [comment]
Ok, great :+1: 
I will make changes soon...
