### ISSUE TITLE
Some pull-requests are missing from the global "Issues/Created" view.

### ISSUE THREAD

**Issue by juherr** [gitskarios/Gitskarios#563]
I expect to see all my created issues/pull-requests in the global "Issues/Created" view but it is not the case. For example, https://github.com/scribejava/scribejava/pull/696 is missing.

**Comment by alorma** [comment]
I know that some issues are missing, but this is api fault :(

Maybe this issue belongs to an organization, and you didn't published your membership?

**Comment by juherr** [comment]
Maybe you don't use the best api to do it because I'm able to see all pull-requests and issues in [OctoDroid](https://github.com/slapperwan/gh4a)

**Comment by alorma** [comment]
well, so i don't know which api use :s

**Comment by juherr** [comment]
👍
