### ISSUE TITLE
Bugs in 4.4.2

### ISSUE THREAD

**Issue by MelvynEzi** [gitskarios/Gitskarios#566]
Retry text is black and unreadable in dark theme.<br />![Screenshot_2016-09-11-13-19-00.png](http://i.imgur.com/q5LPmum.png)<br /><br />Some releases are missing.<br />![Screenshot_2016-09-11-13-19-47.png](http://i.imgur.com/2ckZf4E.png)<br />![Screenshot_2016-09-11-13-29-11.png](http://i.imgur.com/aa0Qgrz.png)<br /><br /><br />Markdown files text is black and unreadable in dark theme.<br />![Screenshot_2016-09-11-13-22-13.png](http://i.imgur.com/7VI3lA1.png)<br /><br />Title of action bar will display the wrong title after navigating through tabs. As seen in the first 2 screenshots.<br /><br />Tab action bar icons are sometimes swapped. Branches should always be on the left.<br />![Screenshot_2016-09-13-05-07-55.png](http://i.imgur.com/WeuR2zC.png)<br /><br />Unable to open PR or issues by deleted accounts (ghost).

**Comment by ghost** [comment]
Adding to this :

•Clicking on any issues in the issues tab crashes Gitskarios

•Seeing Closed issues then refreshes and shows no issues.

**Comment by MelvynEzi** [comment]
Unable to produce above mentioned issues. Maybe you can open your own issue with the stack trace for the crash.

**Comment by mariobrostech** [comment]
Just search for a repository and type nothing in. You'll see the same thing as in the screenshoot!

**Comment by MelvynEzi** [comment]
Tab action bar icons are sometimes swapped. Branches should always be on the left.

**Comment by MelvynEzi** [comment]
@alorma updated

**Comment by farbodsz** [comment]
Shouldn't these all be reported as separate issues?

**Comment by alorma** [comment]
One issue per bug, please
