### ISSUE TITLE
Wrong user events

### ISSUE THREAD

**Issue by juherr** [gitskarios/Gitskarios#569]
App version: 5268c3a

If you scroll the events of a user, you'll see not user events after a moment.

For example, on @LetItRock 's events:

Until

> 5 days ago: "LetItRock deleted branch dev/.... at grapehacks/...."

only user related events, then

> 3 min ago: "juherr commented on issue gitskarios/..."

After, only not user related events.

**Comment by LetItRock** [comment]
This will be fixed with PR #570.
