### ISSUE TITLE
Incorrect Toolbar tab names

### ISSUE THREAD

**Issue by farbodsz** [gitskarios/Gitskarios#571]
The texts "Overview", "Source", "Commits", "Issues", etc display on incorrect tabs. I.e. they don't correspond.

**Comment by alorma** [comment]
Where?

Those tabs should show an icon instead of titles

**Comment by farbodsz** [comment]
I mean like the Toolbar text when tabs change. Sorry, I wasn't very clear when I mentioned. 

![Screenshot_2016-09-14-20-11-29.png](http://i.imgur.com/IAY5Abz.png)

![Screenshot_2016-09-14-20-11-39.png](http://i.imgur.com/yD10mFb.png)

**Comment by alorma** [comment]
Oh ok

I will fix asab

**Comment by farbodsz** [comment]
I've updated my previous comment to show screenshots if that helps. Thanks ;)

**Comment by alorma** [comment]
Fixed
