### ISSUE TITLE
unable to edit after post 

### ISSUE THREAD

**Issue by GeorgeWL** [gitskarios/Gitskarios#575]
https://github.com/ccrama/Slide/issues/2160<br /><br />https://streamable.com/xq21

**Comment by alorma** [comment]
? please, explain the problem

**Comment by GeorgeWL** [comment]
when I attempt to edit a comment on an issue,  the edit doesn't show as being made in the interface. 

And it doesn't propagate to the web version either.

**Comment by MelvynEzi** [comment]
I can confirm. I had to use the browser on desktop version to edit the comment.

**Comment by MelvynEzi** [comment]
@alorma this is a functionality breaking issue. editing a freshly posted comment will not change the comment, sometimes even stating that its not ready.

**Comment by alorma** [comment]
Test comment

**Comment by alorma** [comment]
Mmm, i've updated an issue comment (comment above), and it changed on the web

**Comment by MelvynEzi** [comment]
Test edited 1

**Comment by MelvynEzi** [comment]
Test edited 2

**Comment by MelvynEzi** [comment]
Hmm.. seems like when having a bad connection causes the changes to be lost when attempting to edit.

**Comment by MelvynEzi** [comment]
Somehow, some comments (in another pull request of another repo) would only show a toast "Not ready"

**Comment by GeorgeWL** [comment]
Could it be something as simple as the API being slow to respond occasionally?

**Comment by MelvynEzi** [comment]
"Not ready" toast shows even after 1 week.

**Comment by GeorgeWL** [comment]
I just had a new one.  edit causes app crash, I guess it's a new issue.

**Comment by GeorgeWL** [comment]
#584

**Comment by webmaster33** [comment]
I also had crash, when tapping the edit icon.

**Comment by alorma** [comment]
Fixed

**Comment by ghost** [comment]
Nope for me.

**Comment by alorma** [comment]
I not deployed it to production yet....

**Comment by MelvynEzi** [comment]
Edit: solved stacktrace

**Comment by alorma** [comment]
O_o, well, it's other crash

**Comment by webmaster33** [comment]
Test message. Edited.

**Comment by webmaster33** [comment]
Now comment editing works for me, doesn't crash. The only issue is, that issue is not refreshing automatically, after edit was submitted. 
Version 4.4.8.
Hmmm. Now refreshed automatically after editing.

**Comment by MelvynEzi** [comment]
You'll have issues editing comments on PRs and issues in repos that you don't own (other than this).

**Comment by webmaster33** [comment]
This is not my issue, but still does not crash, when editing. Also I don't see edit icon on other comments, just mine.

**Comment by alorma** [comment]
So, can i close the issue?

**Comment by webmaster33** [comment]
This seems to work in last version. Edited.
