### ISSUE TITLE
Repository 'releases' tab missing some releases

### ISSUE THREAD

**Issue by farbodsz** [gitskarios/Gitskarios#576]
A separate issue created from one mentioned in #566 by @DJCrapsody.
<br />
<br /><img src="https://camo.githubusercontent.com/11abb5fc1ff79cd36c7fb016935bdc52b01a30bb/687474703a2f2f692e696d6775722e636f6d2f32636b5a6634452e706e67"/>
<br />
<br />Compared to the actual (from the webpage):
<br />
<br /><img src="https://camo.githubusercontent.com/4c0d492a74b8bbd27f89d69543cc196452152448/687474703a2f2f692e696d6775722e636f6d2f6161305167727a2e706e67"/>

**Comment by LetItRock** [comment]
From API reference which application use: "This returns a list of releases, which does not include regular Git tags that have not been associated with a release. To get a list of Git tags, use the Repository Tags API."
Do we want to display also tags here @alorma ?

**Comment by alorma** [comment]
Yes, i think we should merge tags and releases into a single list

**Comment by LetItRock** [comment]
Ok, but we want to highlight releases on this list?

**Comment by alorma** [comment]
Somehow, yes :)

Any doubt contact me on slack

**Comment by LetItRock** [comment]
Ok :)

**Comment by LetItRock** [comment]
Will be fixed with PR:
https://github.com/gitskarios/Gitskarios/pull/583
