### ISSUE TITLE
new issue with editing comments: crash upon attempting an edit

### ISSUE THREAD

**Issue by GeorgeWL** [gitskarios/Gitskarios#584]
Upon attempting to edit a comment on any issue, the app crashes to the Failure Screen (with the upside down bug)  and then requests a restart. <br /><br />The edit made doesn't propagate to the web or the app.

This is one the beta version of the app, on android N.

 <br /><br />https://streamable.com/rmyf<br /><br />Doesn't seem to happen in all instances <br /><br />Error message:<br /><br />

`Build version: 4.4.4 Build date: 1979-11-30 00:00:00 Current date: 2016-10-03 10:57:42 Device: Sony E6653 Stack trace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alorma.github/com.alorma.github.ui.activity.ContentEditorActivity}: java.lang.ClassCastException: com.alorma.github.sdk.bean.dto.response.ShaUrl cannot be cast to com.alorma.github.sdk.bean.dto.response.GithubComment   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)    at android.app.ActivityThread.access$900(ActivityThread.java:154)   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:234)  at android.app.ActivityThread.main(ActivityThread.java:5526)    at java.lang.reflect.Method.invoke(Native Method)   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)Caused by: java.lang.ClassCastException: com.alorma.github.sdk.bean.dto.response.ShaUrl cannot be cast to com.alorma.github.sdk.bean.dto.response.GithubComment  at com.alorma.github.sdk.bean.issue.IssueStoryComment.(IssueStoryComment.java:50)   at com.alorma.github.sdk.bean.issue.IssueStoryComment$1.createFromParcel(IssueStoryComment.java:57) at com.alorma.github.sdk.bean.issue.IssueStoryComment$1.createFromParcel(IssueStoryComment.java:54) at android.os.Parcel.readParcelable(Parcel.java:2398)   at android.os.Parcel.readValue(Parcel.java:2295)    at android.os.Parcel.readArrayMapInternal(Parcel.java:2645) at android.os.BaseBundle.unparcel(BaseBundle.java:221)  at android.os.BaseBundle.getString(BaseBundle.java:920) at com.alorma.github.ui.activity.ContentEditorActivity.onCreate(ContentEditorActivity.java:133) at android.app.Activity.performCreate(Activity.java:6285)   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)   ... 9 more`

**Comment by webmaster33** [comment]
Is it fixed?

**Comment by alorma** [comment]
Yes

**Comment by webmaster33** [comment]
Great! Quick job!
