### ISSUE TITLE
Shouldn't we remove TravisCI?

### ISSUE THREAD

**Issue by pkramme** [gitskarios/Gitskarios#586]
Shouldn't we remove Travis when it fails everytime? Why is it in?

**Comment by alorma** [comment]
Hi.

No, travis not always fail, it fail for PR's because there is an encryptation made by my keys on it, and i don't know why it fails for you :S

If fails in the dev branch is ok, so it can't compile.

Travis CI is used to deploy the application to play store, so no, we re not going to remove it

**Comment by pkramme** [comment]
Didn't know the Appstore workflow. Thanks.
