### ISSUE TITLE
Display repository on Issues/Created page

### ISSUE THREAD

**Issue by webmaster33** [gitskarios/Gitskarios#594]
_Issue:_<br />Display repository information on Issues/Created page. Otherwise user doesn't know to which repository the issue belongs to. <br /><br /><br />> App version<br />><br />> Git build hash from settings:<br />><br />> Device<br />><br />> Device android version<br /><br /><br />_Steps to reproduce:_<br /><br /><br /><br /><br />_Crash (optional):_<br /><br /><br />_Screenshots_<br /><br /><br />

**Comment by webmaster33** [comment]
You close everything without resolving?

**Comment by alorma** [comment]
@webmaster33:
<img width="374" alt="captura de pantalla 2016-10-18 a las 18 52 22" src="https://cloud.githubusercontent.com/assets/887462/19487669/06811f22-9564-11e6-95c0-bc06adf93ad6.png">

This means is closed on a commit, so it's fixed

**Comment by webmaster33** [comment]
Your text is very small after @webmaster33, unreadable. Could be fixed? Sorry not starting a new issue for it, but this is the place where it happened.

**Comment by alorma** [comment]
????

**Comment by webmaster33** [comment]
Can post a screenshot here?

**Comment by ghost** [comment]
create a new issues. it's the better way.

**Comment by alorma** [comment]
I not understand, what's the problem @webmaster33 ?? If there's another bug, please open a new issue

**Comment by webmaster33** [comment]
Ok, posted a new issue. Thanks for fixing this closed issue.
