### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by webmaster33** [gitskarios/Gitskarios#595]
Build version: 4.4.4 <br />Build date: 1979-11-30 00:00:00 <br />Current date: 2016-10-17 12:28:12 <br />Device: Samsung GT-I9305 <br />Rom: MIUI V5 4.6.20<br /><br />Stack trace:  <br />java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alorma.github/com.alorma.github.ui.activity.ContentEditorActivity}: java.lang.ClassCastException: com.alorma.github.sdk.bean.dto.response.ShaUrl cannot be cast to com.alorma.github.sdk.bean.dto.response.GithubComment<br />    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100)<br /> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)<br />  at android.app.ActivityThread.access$600(ActivityThread.java:140)<br /> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227)<br />   at android.os.Handler.dispatchMessage(Handler.java:99)<br />    at android.os.Looper.loop(Looper.java:137)<br />    at android.app.ActivityThread.main(ActivityThread.java:4898)<br />  at java.lang.reflect.Method.invokeNative(Native Method)<br />   at java.lang.reflect.Method.invoke(Method.java:511)<br />   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)<br />   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)<br />   at dalvik.system.NativeStart.main(Native Method)<br />Caused by: java.lang.ClassCastException: com.alorma.github.sdk.bean.dto.response.ShaUrl cannot be cast to com.alorma.github.sdk.bean.dto.response.GithubComment<br /> at com.alorma.github.sdk.bean.issue.IssueStoryComment.<init>(IssueStoryComment.java:50)<br />   at com.alorma.github.sdk.bean.issue.IssueStoryComment$1.createFromParcel(IssueStoryComment.java:57)<br />   at com.alorma.github.sdk.bean.issue.IssueStoryComment$1.createFromParcel(IssueStoryComment.java:54)<br />   at android.os.Parcel.readParcelable(Parcel.java:2103)<br /> at android.os.Parcel.readValue(Parcel.java:1965)<br />  at android.os.Parcel.readMapInternal(Parcel.java:2226)<br />    at android.os.Bundle.unparcel(Bundle.java:223)<br />    at android.os.Bundle.getString(Bundle.java:1055)<br />  at com.alorma.github.ui.activity.ContentEditorActivity.onCreate(ContentEditorActivity.java:133)<br />   at android.app.Activity.performCreate(Activity.java:5184)<br /> at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1083)<br />    at com.lbe.security.service.core.client.internal.InstrumentationDelegate.callActivityOnCreate(InstrumentationDelegate.java:76)<br />    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)<br /> ... 11 more

**Comment by alorma** [comment]
Unable to reproduce

**Comment by ghost** [comment]
It have a custom rom. it can create problem?

**Comment by alorma** [comment]
Describe steps to reproduce

**Comment by webmaster33** [comment]
- go to Notifications page, 
- tap an Issue, 
- add a comment
- try to edit comment immediately, by tapping the Edit icon.
- CRASH

**Comment by alorma** [comment]
Thanks

**Comment by ghost** [comment]
NOT CRASH FOR ME!

**Comment by webmaster33** [comment]
I was able to reproduce this bug under MIUI v5 4.6.20 (Android v4.1.1).

**Comment by alorma** [comment]
Testing

**Comment by ghost** [comment]
see my old comment (20 minutes ago)

**Comment by webmaster33** [comment]
Were you able to reproduce?

**Comment by alorma** [comment]
Yes, and now it's fixed

**Comment by webmaster33** [comment]
Thank you very much! You are very quick developer!

**Comment by lilicoding** [comment]
Is there someone can explain to me, why the build date is 1979-11-30 00:00:00, which does not make sense, right?
