### ISSUE TITLE
Inserted image size is too small

### ISSUE THREAD

**Issue by webmaster33** [gitskarios/Gitskarios#598]
Inserted image size is too small. 
Screenshot:

![Screenshot_2016-10-18-19-05-02.png](http://i.imgur.com/X7a8yGu.png)

**Comment by webmaster33** [comment]
Do you see your inserted image in your comment?
It is shrinked too much.

**Comment by ghost** [comment]
it's very small, but you can open this with a click.

**Comment by webmaster33** [comment]
It would be possible to give a bigger image size, as I see the image itself is big.

**Comment by alorma** [comment]
it comes as html tag, and now i don't know how to make it bigger :S

**Comment by webmaster33** [comment]
This way? 
You set the size of the image:
`<img src="img.jpg" style="width: 100px; height: 50px;" width="100" height="50">`

**Comment by alorma** [comment]
I know how to set an image in html, but i should parse html content to search `<img`tag, and update properties..., not easy

**Comment by webmaster33** [comment]
Well, if the image tag comes from github program, then likely the output is always the same. So you can identify <img tag and find height and width attributes easily with regular expression (don't know java).

**Comment by webmaster33** [comment]
What help is needed?

**Comment by alorma** [comment]
Well. I get html content from github, app should replace the `<img` width and height

**Comment by webmaster33** [comment]
Yes. Can I help?

**Comment by alorma** [comment]
send me a email to `gitskarios@gmail.com` , i will add you to slack so we can discuss it

Thanks!

**Comment by webmaster33** [comment]
Sent

**Comment by alorma** [comment]
Fixed :)

![Screenshot_20161120-151856.png](http://i.imgur.com/jsPGVRZ.png)

Good enough @webmaster33?

**Comment by webmaster33** [comment]
Great! Were the changes pushed to github?

**Comment by alorma** [comment]
Yes

**Comment by alorma** [comment]
https://github.com/gitskarios/Gitskarios/commit/d35260d1ade9234d1ee285223d0dc7603b3e0f30

**Comment by webmaster33** [comment]
Thanks! Great job!
