### ISSUE TITLE
Different divider height

### ISSUE THREAD

**Issue by rocboronat** [gitskarios/Gitskarios#60]
The dividers of the source list and the commits one has differeint height

![2015-04-01 11 04 12](https://cloud.githubusercontent.com/assets/456499/6939745/caf3ed66-d86f-11e4-96d4-7c3b1bd3c77b.png)

**Comment by alorma** [comment]
![device-2015-07-12-202030](https://cloud.githubusercontent.com/assets/887462/8639226/86a50ab4-28d3-11e5-96e8-a7954fe73944.png)

Fixed
