### ISSUE TITLE
Notifications page, items not hiding after they was viewed

### ISSUE THREAD

**Issue by webmaster33** [gitskarios/Gitskarios#600]
On Notifications page, items not hiding after they was viewed. 

I have to tap the 3 point icon, tap Make as read to hide it. 

1) Could be possible to make as read after it was opened? 

2) Also put a menu item on the page viewing the issue, to make as read? 

Thanks!

**Comment by alorma** [comment]
1) You can configure it in settings

2) Not for now, i need a thread_id and api doesn't provide it

**Comment by ghost** [comment]
today we have found 10 bug XD

**Comment by webmaster33** [comment]
1) uhm, sorry, I missed this option :-(

**Comment by webmaster33** [comment]
2) not sure, if you need anything special for this. Just a timestamp, when user did open the issue. You store it locally. Then query the timestamp of the last comment. If timestamp of last comment is bigger, then this issue has new comment. Does it make sense?

**Comment by alorma** [comment]
To mark notification as read i need a thread_id

**Comment by webmaster33** [comment]
thread_id = issue id?

**Comment by alorma** [comment]
no, is not the same.

https://developer.github.com/v3/activity/notifications/
