### ISSUE TITLE
Attach APK to releases?

### ISSUE THREAD

**Issue by IzzySoft** [gitskarios/Gitskarios#604]
As this is open source (but not on F-Droid): Would you consider attaching the `.apk` file to the `releases/` for people without playstore access? Just the "stable" ones would be fine, though "usable Betas" might be welcome, too :)

**Comment by gitskarios-dev** [comment]
i had that, but it's not working now :$, i will fix it soon

**Comment by IzzySoft** [comment]
Good to read! Once done, feel free to close this issue (which will send me a notification then so I will know ;) Thumbs up!

**Comment by IzzySoft** [comment]
Just seeing a new release today (congrats!), so may I ask if the APK was just accidentally forgotten?

**Comment by alorma** [comment]
Hi @IzzySoft 

No, it's not forgotten, i don't know why but travis is unable to find apk files.... i'm checking it :$

**Comment by IzzySoft** [comment]
@alorma fingers crossed then! And waiting patiently. Next bump not before end of month :)

**Comment by alorma** [comment]
Should work now, check it on https://github.com/gitskarios/Gitskarios/releases/tag/v.4.6.1

**Comment by IzzySoft** [comment]
Indeed it does, thanks! Just added it [here](https://apt.izzysoft.de/fdroid/index/apk/com.alorma.github), and updated it [here](https://android.izzysoft.de/applists/category/named/network_techsites#group_910) :)

**Comment by alorma** [comment]
Oh, Thanks :D

**Comment by IzzySoft** [comment]
You're welcome! If one day you chose to have the app in the official F-Droid repo and want me to remove it from mine, just drop me a note. Due to the size, my repo will only have 1 version of Gitscarios, as my "per-app-limit" is ~20MB (so for apps up to 10MB there are the 2 latest versions, and for apps smaller than 7MB 3 versions kept).

**Comment by alorma** [comment]
it's ok :b, if there's an option to upload to f-droid automatic, i will try it

**Comment by IzzySoft** [comment]
You can't upload your APK there. But you can have them compile it from your sources. It will then be signed with their key. I can't give you details on the process (I'm no dev) – but good luck if you go that road. Might take a little until they pick it up, and rules are a bit stronger – but of course you reach more users there, and the trust is higher as they "check the code" (I can only have VirusTotal check the `.apk` files ;)
