### ISSUE TITLE
Show app version in About menu item 

### ISSUE THREAD

**Issue by webmaster33** [gitskarios/Gitskarios#605]
Should show app version in About menu item.

**Comment by alorma** [comment]
What About section you mean?

**Comment by webmaster33** [comment]
Which is missing :-)

**Comment by MelvynEzi** [comment]
Should also remove changelog if there isn't any intention of updating it. It's misleading. App Version in the Settings page should be fine.

**Comment by webmaster33** [comment]
Version is also fine in Settings, just thought that About is a standard in software industry.

**Comment by webmaster33** [comment]
I still miss this small change. 
I don't know, which version I do use.

**Comment by gitskarios-dev** [comment]
Available on release 4.5.5 (publishing now)

**Comment by webmaster33** [comment]
Thanks!
