### ISSUE TITLE
App crash, force restart when libked to comment in code

### ISSUE THREAD

**Issue by rancidfrog** [gitskarios/Gitskarios#609]
On events tab, clicked on a link to a comment on a commit - crashes app, force restart:<br /><br />```<br />java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String core.User.getLogin()' on a null object reference<br />    at core.repositories.Repo.toInfo(Repo.java:333)<br />    at com.alorma.github.ui.fragment.events.EventsListFragment.onItemSelected(EventsListFragment.java:380)<br />    at com.alorma.github.ui.fragment.events.EventsListFragment.onItemSelected(EventsListFragment.java:60)<br />    at com.alorma.github.ui.adapter.events.holders.EventViewHolder.lambda$populate$0(EventViewHolder.java:39)<br />    at com.alorma.github.ui.adapter.events.holders.EventViewHolder.access$lambda$0(EventViewHolder.java)<br />    at com.alorma.github.ui.adapter.events.holders.EventViewHolder$$Lambda$1.onClick(Unknown Source)<br />    at android.view.View.performClick(View.java:5609)<br />    at android.view.View$PerformClick.run(View.java:22262)<br />    at android.os.Handler.handleCallback(Handler.java:751)<br />    at android.os.Handler.dispatchMessage(Handler.java:95)<br />    at android.os.Looper.loop(Looper.java:154)<br />    at android.app.ActivityThread.main(ActivityThread.java:6077)<br />    at java.lang.reflect.Method.invoke(Native Method)<br />    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)<br />    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)<br />```<br />

**Comment by rancidfrog** [comment]
When there is an event of comment in code, app crashes or has error can not access

**Comment by alorma** [comment]
Can you provide the comment event url? Thanks

**Comment by rancidfrog** [comment]
For example, in the following [PR](https://github.com/sonyxperiadev/camera/pull/30) there is comment in code which causes app popup:
![](https://s17.postimg.org/4r01yeptb/Screenshot_20161101_221324.png) 

For the other link, which causes restart app popup, it cannot be copied.
I tried long-clicking event in app but nothing happens.
Events do not appear in web

**Comment by alorma** [comment]
Ok, it's enough, thanks

**Comment by rancidfrog** [comment]
Is it possible to have longclick event to copy link, such that you can open in browser or report broken links?

**Comment by alorma** [comment]
yes, i will implement that

**Comment by rancidfrog** [comment]
The other event I believe links to this, https://github.com/oshmoun/kernel/commit/67aac2ff05
Causing app to restart:
![](https://s16.postimg.org/4ed0qo9xh/Screenshot_20161101_223600.png)

**Comment by rancidfrog** [comment]
It works now when I click the link above, but it does not show comment and if you open it in web browser you will see a comment, which causes app to crash when linking to it via events

**Comment by alorma** [comment]
Hi @rancidfrog .

Checking that PR, i see it shows `unknown repository` on head branch.

What does it means? Is the head repository private?
