### ISSUE TITLE
Search in issues

### ISSUE THREAD

**Issue by Hauwertlhaufn** [gitskarios/Gitskarios#61]
Is it possible to add the search for the issues?
On some big projects it is hard to see in Gitskarios, if a issue already exists.

**Comment by rummik** [comment]
Searching from mobile on GitHub has been pretty difficult anyway, so it'd be nice to finally have a way to do that.

**Comment by alorma** [comment]
Sure.

I will implepent that in a future releases.

Thanks

**Comment by alorma** [comment]
I read the documentation about issues:

https://developer.github.com/v3/issues/#custom-media-types

I canot find any way to do what you request.

Sorry, this will not be implemented

**Comment by Hauwertlhaufn** [comment]
I think we could use that as a workaround:
https://developer.github.com/v3/search/#search-issues
The api should look something like that then:
```
https://api.github.com/search/issues?q=gitskarios+label:bug+language:java+state:open&sort=created&order=asc
```

**Comment by alorma** [comment]
Uhmmm...

Sounds good, i will check it soon, thanks.

**Comment by Hauwertlhaufn** [comment]
No problem. Hope it works with that.
