### ISSUE TITLE
Repositories should start with optional starred tab

### ISSUE THREAD

**Issue by webmaster33** [gitskarios/Gitskarios#610]
When I change to Repositories menu, it should switch to the Starred tab automatically. 

Or at least add an option to be able to select the default tab at Repositories menu. 

Thanks!

**Comment by alorma** [comment]
Done

**Comment by webmaster33** [comment]
Great! Thanks very much!

**Comment by webmaster33** [comment]
In settings I see only Default tab option. Is it the same or a new feature?

**Comment by alorma** [comment]
Mmm yes, that's the option to start repository with a selected tab
