### ISSUE TITLE
Text entered into comment field is not copied, when maximizing to full screen 

### ISSUE THREAD

**Issue by webmaster33** [gitskarios/Gitskarios#611]
Text entered into comment field is not copied, when maximizing to full screen. 

Reproducing steps:
1) start a comment 
2) enter text into comment field 
3) press maximize icon 
4) on full screen you don't see the text you entered in comment field

**Comment by alorma** [comment]
Testing

**Comment by webmaster33** [comment]
Thanks very much! 
Confirming that works fine.
