### ISSUE TITLE
notifications keep showing up

### ISSUE THREAD

**Issue by mmoayyed** [gitskarios/Gitskarios#612]
Notifications on repositories keep showing up again and again unless the entry is marked as read on github.

**Comment by webmaster33** [comment]
There is an option in the settings to change this behavior.

**Comment by mmoayyed** [comment]
Thanks! That works.

**Comment by mmoayyed** [comment]
actually I take that back. that option is turned on but notifications keep showing up again and again even after I have viewed and browsed to the issue or repo that had the notification

**Comment by alorma** [comment]
You can mark them as readed

**Comment by mmoayyed** [comment]
Sure, but if a notification comes up and I browse to it via the app, shouldn't the notification automatically be marked as read?

**Comment by alorma** [comment]
There's no option to mark as read, if you visit issue from notification directly (android notification), but in the notifications screen you can mark them as read.

BTW, there's a setting on Settings screen, to mark them read automatically
