### ISSUE TITLE
Patching a kernel (how to?)

### ISSUE THREAD

**Issue by webmaster33** [gitskarios/Gitskarios#620]
How can I patch a kernel, if it is not available as recovery zip format?

**Comment by alorma** [comment]
¿? What you mean

**Comment by webmaster33** [comment]
Dual Boot Patcher can only patch recovery zip files. But if it is a tar.gz, it can't.

**Comment by alorma** [comment]
Hi @webmaster33 i guess you are not in the correct repository. This is Gitskarios, not a... linux / android boot patcher :S

**Comment by webmaster33** [comment]
Uhm. Sorry. Can I delete the issue?

**Comment by alorma** [comment]
Closed :D
