### ISSUE TITLE
Can not create new issue, if going through Repo link

### ISSUE THREAD

**Issue by webmaster33** [gitskarios/Gitskarios#621]
1) open an issue <br />2) tap the Repo link <br />3) tap the issues tab<br />4) the new issue icon is missing on that page <br /><br />Could be possible to fix it?

**Comment by alorma** [comment]
What is the assignee link?

**Comment by webmaster33** [comment]
Ok, not the assignee, but the link below, the repo link.

**Comment by alorma** [comment]
Oh, ok you mean the gitskarios/gitskarios link from issue?

**Comment by webmaster33** [comment]
Yeah

**Comment by alorma** [comment]
Done, will release soon

**Comment by webmaster33** [comment]
Thanks very much! You're amazing, very quick developer!
