### ISSUE TITLE
Source code not show last reference

### ISSUE THREAD

**Issue by KimWahlman** [gitskarios/Gitskarios#630]
*Issue:* Repositories doesn't show the current version of the repository. 
<br />> App version 4.5.7
<br />> Git build hash from settings: 9e00da5
<br />> Device: LG G3
<br />> Device android version: 5.0 
<br />
<br />*Steps to reproduce:*
<br />1. Open the application
<br />2. Open a repository
<br />3. Select a branch if you keep your master branch tidy
<br />4. Select "View Code"
<br />5. Only the first commit seem to be displayed. 
<br />
<br />The screenshot below show what the app is seeing and the other one what the "open in browser" is showing. And as you can see it show two different things in the app and the browser.
<br />
<br />*Screenshots*
<br />![2](https://cloud.githubusercontent.com/assets/43886/20180074/23ecb236-a759-11e6-9352-6af2cf958446.png)
<br />![1](https://cloud.githubusercontent.com/assets/43886/20180073/23ec3fa4-a759-11e6-83ac-d3229a984448.png)
<br />

**Comment by alorma** [comment]
WOW, that's a BUG!
