### ISSUE TITLE
Cannot change branch or view source code in the top repository

### ISSUE THREAD

**Issue by KimWahlman** [gitskarios/Gitskarios#632]
*Issue:* Cannot view branches and source code in the top repository. 
<br />
<br />> App version: 4.6.6
<br />> Git build hash from settings: 9c5087d
<br />> Device LG 3G
<br />> Device android version 5.0
<br />
<br />*Steps to reproduce:*
<br />This only seem to happen on the top repository, I don't know if it matters that it is at the top. I don't really know how to explain it other than that. Check the video below.
<br />
<br />*Video:*
<br />Video showing the problem.
<br />https://www.youtube.com/watch?v=Vv_RUG-RQkw

**Comment by alorma** [comment]
Fixed
