### ISSUE TITLE
Similar issue as in #630 has reappeared. 

### ISSUE THREAD

**Issue by KimWahlman** [gitskarios/Gitskarios#641]
*Issue:* Repositories doesn't show the current version of the repository.

> App version: 4.6.8
> Git build hash from settings: 26c2b51
> Device: LG 3G
> Device android version: 5.0

*Steps to reproduce:* Pretty much the same as in #630, I also tried two other repositories, one worked the other didn't. 
*Screenshots*: http://imgur.com/a/NrLW3

*Additional comments*: Seems like some works, others doesn't. I do not know what could cause this.

**Comment by alorma** [comment]
Released
