### ISSUE TITLE
App reloads readme section when the user switches back to it, losing the user's place

### ISSUE THREAD

**Issue by smiley** [gitskarios/Gitskarios#72]
I don't think the tab holding the "README" contents should be reloaded when the user returns to the app. It loses the user's place in the file, which makes README-based repos like "ripienaar/free-for-dev" hard to read.

**Comment by smiley** [comment]
On second thought, you can ask the server for the latest version & see if it responds with "no difference" or with a new version. If Github's API supports HTTP caching, this might help decide whether this should be reloaded or not.

**Comment by alorma** [comment]
Will check about to keep data, it's something about reload content when activity restarts.

**Comment by smiley** [comment]
No, the activity persists -- I can see the older version of the readme as it reloads. It just picks up on the return & reloads it anyway.
