### ISSUE TITLE
Some repos are duplicated several times 

### ISSUE THREAD

**Issue by vinz243** [gitskarios/Gitskarios#76]
Hi,

In My Repositories section , UnrealEngine repos are displayed several times. I'll try to add a screenshot soon ;)

**Comment by vinz243** [comment]
here it is ![screen](http://imgur.com/nR4MF9X)

**Comment by alorma** [comment]
@vinz243 image cannot be loaded

**Comment by vinz243** [comment]
Oh sorry I updated the post ;)

**Comment by alorma** [comment]
O_o! Really weird!

Is this project a fork? Or some kind of "mirror" from another one?

**Comment by vinz243** [comment]
Nope I don't think so. It's only UnrealEngine repo (from EpicGames user). And I didn't even forked it. Only I'm in EpicGames org.

**Comment by alorma** [comment]
Is that fixed @vinz243?

**Comment by vinz243** [comment]
Oops sorry y it's fixed thanks :)
