### ISSUE TITLE
Material icon

### ISSUE THREAD

**Issue by afollestad** [gitskarios/Gitskarios#85]
A Material icon is definitely needed.

I'd recommend someone like Pedro Peguero Jr. (the designer of Moonshine icon pack, he's a friend of mine and I designed the dashboard UI for Moonshine). https://plus.google.com/+PedroPegueroJr

**Comment by alorma** [comment]
Sure! I know that i need an icon :$

I'm on talk with a designer, but it's not sure.

If you can talk with him it would be awesome :) Thanks!
