### ISSUE TITLE
Names for repositories are cut off if their long in "My Repositories"

### ISSUE THREAD

**Issue by afollestad** [gitskarios/Gitskarios#87]
You should be using a RelativeLayout, and make the name stay to the left of the elements at the far right. I can help out when I have a little time.

E.g the third repo:

![ex](https://cloud.githubusercontent.com/assets/1820165/7107741/0e4a9c9a-e135-11e4-9be6-81bba5af2433.png)

**Comment by alorma** [comment]
Uhmm. It SHOULD be two lined in that case :o

I will check and fix ite unless you do it before :)
