### ISSUE TITLE
Some commit date are showing authored date.

### ISSUE THREAD

**Issue by robertmathew** [gitskarios/Gitskarios#89]
![screenshot_2015-04-14-12-34-39](https://cloud.githubusercontent.com/assets/2344947/7132111/ecc3946c-e2a3-11e4-895c-07ce489fc5ea.png)
![20150414_123509](https://cloud.githubusercontent.com/assets/2344947/7132115/f1a2f86a-e2a3-11e4-851f-aad0f03eb1cd.jpg)

Commit on 13 April is showing authored date 8 Feb.

**Comment by alorma** [comment]
HI.

Thanks for that, can you give me the repository where it happens? I will test it soon

**Comment by robertmathew** [comment]
https://github.com/TeamBliss-LP/android_packages_apps_Settings/commits/lp5.1

**Comment by alorma** [comment]
thanks
