### ISSUE TITLE
This project doesn't support Chinese in Markdown display

### ISSUE THREAD

**Issue by mountainguan** [gitskarios/Gitskarios#96]
Chinese in readme.md may display into error code.But English display well.Could you please fix that on next version?

**Comment by mountainguan** [comment]
This problem also happen in issue content,but not in issue header.

**Comment by pcqpcq** [comment]
sounds like the same problem with #65 @alorma

**Comment by alorma** [comment]
Thanks guys!

I will take a look in the https://github.com/alorma/Gitskarios/milestones/2.5.0 milestone :)

**Comment by mountainguan** [comment]
issues content still couldn't display Chinese.

**Comment by alorma** [comment]
Hi.

Can you give me example repositories where this happen?

**Comment by mountainguan** [comment]
https://github.com/cuber/ngx_http_google_filter_module here is the example
